import {
  apiClient,
  unwrapApiData,
  unwrapApiResponse,
} from "@/lib/axios";
import type {
  AutoGenerateDoctorShiftsResponse,
  BackendGroupedDoctorShifts,
  BackendDoctorShift,
  BackendPaginatedDoctorShifts,
  BulkGenerateDoctorShiftsInput,
  CheckDoctorShiftConflictsInput,
  CreateDoctorShiftInput,
  DoctorAvailabilityResponse,
  DoctorShiftApiResponse,
  DoctorShiftConflictResponse,
  DoctorShiftItem,
  DoctorShiftListResult,
  DoctorShiftStatus,
  GetDoctorAvailabilityParams,
  GetDoctorShiftsParams,
  GetGroupedDoctorShiftsParams,
  GetWeeklyDoctorShiftsParams,
  UpdateDoctorShiftInput,
  WeeklyUpdateDoctorShiftsInput,
  WeeklyUpdateDoctorShiftsResponse,
} from "./doctor-shifts.types";

const ENDPOINT = "/management/shifts";

function compactObject(
  value: Record<string, unknown>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value).filter(
      ([, item]) =>
        item !== undefined &&
        item !== null &&
        item !== "",
    ),
  );
}

function toStringValue(value: unknown): string {
  if (value === undefined || value === null) {
    return "";
  }

  return String(value).trim();
}

function toNumberValue(value: unknown): number {
  const parsed = Number(value);

  return Number.isFinite(parsed) && parsed >= 0
    ? parsed
    : 0;
}

function toIdRequestValue(value: unknown): string {
  return String(value ?? "").trim();
}

function normalizeTime(value: string): string {
  const [hour = "00", minute = "00"] = String(
    value ?? "",
  )
    .trim()
    .split(":");

  return `${hour.padStart(2, "0")}:${minute.padStart(
    2,
    "0",
  )}`;
}

function normalizeStatus(
  status: string,
): DoctorShiftStatus {
  const normalized = String(status ?? "")
    .trim()
    .toLowerCase();

  if (
    normalized === "available" ||
    normalized === "full" ||
    normalized === "cancelled" ||
    normalized === "off"
  ) {
    return normalized;
  }

  return "available";
}

function normalizeDoctorShift(
  shift: BackendDoctorShift,
): DoctorShiftItem {
  return {
    id: toStringValue(shift.id),
    doctorId: toStringValue(shift.doctorId),
    staffId: toStringValue(shift.staffId),
    roleId: toStringValue(shift.roleId),
    slotId: toStringValue(shift.slotId),
    facilityId: toStringValue(shift.facilityId),
    roomId: toStringValue(shift.roomId),
    shiftDate: toStringValue(shift.shiftDate),
    startTime: normalizeTime(shift.startTime),
    endTime: normalizeTime(shift.endTime),
    maxAppointments: toNumberValue(
      shift.maxAppointments,
    ),
    bookedAppointments: toNumberValue(
      shift.bookedAppointments,
    ),
    status: normalizeStatus(shift.status),
    note: toStringValue(shift.note),
    createdAt: toStringValue(shift.createdAt),
    updatedAt: toStringValue(shift.updatedAt),
    staffName: toStringValue(
      shift.staffName || shift.doctorName,
    ),
    roleName: toStringValue(shift.roleName),
    doctorName: toStringValue(
      shift.doctorName || shift.staffName,
    ),
    doctorTitle: toStringValue(shift.doctorTitle),
    doctorSpecialty: toStringValue(
      shift.doctorSpecialty,
    ),
    facilityCode: toStringValue(
      shift.facilityCode,
    ),
    facilityName: toStringValue(
      shift.facilityName,
    ),
    roomName: toStringValue(shift.roomName),
    roomType: toStringValue(shift.roomType),
    roomTypeId: toStringValue(shift.roomTypeId),
    roomTypeName: toStringValue(
      shift.roomTypeName,
    ),
    slotCode: toStringValue(shift.slotCode),
    slotName: toStringValue(shift.slotName),
  };
}

type DoctorShiftListData =
  | BackendDoctorShift[]
  | BackendPaginatedDoctorShifts
  | {
      days?: Array<{
        date?: string;
        shifts?: BackendDoctorShift[];
      }>;
    };

function normalizeDoctorShiftItems(
  data: DoctorShiftListData,
): DoctorShiftItem[] {
  if (Array.isArray(data)) {
    return data.map(normalizeDoctorShift);
  }

  if ("days" in data && Array.isArray(data.days)) {
    return data.days.flatMap((day) => {
      if (!Array.isArray(day.shifts)) {
        return [];
      }

      return day.shifts.map((shift) =>
        normalizeDoctorShift({
          ...shift,
          shiftDate: shift.shiftDate || day.date || "",
        }),
      );
    });
  }

  return "items" in data && Array.isArray(data.items)
    ? data.items.map(normalizeDoctorShift)
    : [];
}

function normalizeDoctorShiftListResult(
  data: DoctorShiftListData,
  params?: GetDoctorShiftsParams,
): DoctorShiftListResult {
  const items = normalizeDoctorShiftItems(data);

  if (
    !Array.isArray(data) &&
    "items" in data &&
    Array.isArray(data.items)
  ) {
    return {
      items,
      total: Number(data.total) || items.length,
      page: Number(data.page) || params?.page || 1,
      limit:
        Number(data.limit) ||
        params?.limit ||
        Math.max(items.length, 1),
      totalPages:
        Number(data.totalPages) ||
        (items.length > 0 ? 1 : 0),
    };
  }

  const limit =
    params?.limit ?? Math.max(items.length, 1);

  return {
    items,
    total: items.length,
    page: params?.page ?? 1,
    limit,
    totalPages:
      items.length === 0
        ? 0
        : Math.max(1, Math.ceil(items.length / limit)),
  };
}

function toListParams(
  params?: GetDoctorShiftsParams,
): Record<string, unknown> {
  return compactObject({
    doctorId: params?.doctorId?.trim(),
    facilityId: params?.facilityId?.trim(),
    roomId: params?.roomId?.trim(),
    dateFrom: params?.dateFrom,
    dateTo: params?.dateTo,
    status: params?.status,
    page: params?.page,
    limit: params?.limit ?? 20,
  });
}

function toCreatePayload(
  input: CreateDoctorShiftInput,
): Record<string, unknown> {
  return {
    doctorId: input.doctorId.trim(),
    staffId: input.staffId.trim(),
    roleId: toIdRequestValue(input.roleId),
    facilityId: input.facilityId.trim(),
    roomId: input.roomId.trim(),
    slotId: input.slotId.trim(),
    shiftDate: input.shiftDate,
    maxAppointments: input.maxAppointments,
    status: input.status,
    note: input.note.trim(),
  };
}

function toUpdatePayload(
  input: UpdateDoctorShiftInput,
): Record<string, unknown> {
  const payload = compactObject({
    doctorId: input.doctorId?.trim(),
    staffId: input.staffId?.trim(),
    roleId:
      input.roleId === undefined
        ? undefined
        : toIdRequestValue(input.roleId),
    facilityId: input.facilityId?.trim(),
    shiftDate: input.shiftDate,
    maxAppointments: input.maxAppointments,
    status: input.status,
    note: input.note?.trim(),
  });

  if ("roomId" in input) {
    payload.roomId =
      input.roomId === null
        ? null
        : input.roomId?.trim();
  }

  if ("slotId" in input) {
    payload.slotId =
      input.slotId === null
        ? null
        : input.slotId?.trim();
  }

  return payload;
}

function toConflictPayload(
  input: CheckDoctorShiftConflictsInput,
): Record<string, unknown> {
  return compactObject({
    doctorId: input.doctorId.trim(),
    staffId: input.staffId.trim(),
    roleId: toIdRequestValue(input.roleId),
    facilityId: input.facilityId.trim(),
    roomId: input.roomId.trim(),
    slotId: input.slotId.trim(),
    shiftDate: input.shiftDate,
    note: input.note.trim(),
    excludeShiftId: input.excludeShiftId?.trim(),
  });
}

function normalizeSlotAssignments(
  slotAssignments: BulkGenerateDoctorShiftsInput["slotAssignments"],
) {
  return slotAssignments.map((slotAssignment) => ({
    slotId: slotAssignment.slotId.trim(),
    assignments: slotAssignment.assignments.map(
      (assignment) => ({
        staffId: assignment.staffId.trim(),
        roleId: assignment.roleId.trim(),
        roomId: assignment.roomId.trim(),
        workingDays: assignment.workingDays,
        maxAppointments: assignment.maxAppointments,
        status: assignment.status,
      }),
    ),
  }));
}


function toBulkGenerateConfirmPayload(
  input: BulkGenerateDoctorShiftsInput,
): Record<string, unknown> {
  return {
    facilityId: input.facilityId.trim(),
    fromDate: input.fromDate,
    toDate: input.toDate,
    slotAssignments: normalizeSlotAssignments(
      input.slotAssignments,
    ),
    saveOnlyValid: input.saveOnlyValid,
  };
}

function getDoctorShiftApiErrorMessage(
  error: unknown,
): string {
  if (
    typeof error === "object" &&
    error &&
    "response" in error
  ) {
    const response = (
      error as {
        response?: {
          status?: number;
          data?: {
            message?: string | string[];
          };
        };
      }
    ).response;

    const message =
      response?.data?.message;

    if (
      Array.isArray(message)
    ) {
      return message.join(" ");
    }

    if (
      typeof message === "string"
    ) {
      return message;
    }
  }

  return error instanceof Error
    ? error.message
    : "";
}

/**
 * Backend hiện trả 404 khi GET danh sách ca trực không có bản ghi.
 *
 * Với list endpoint, "không có dữ liệu" là danh sách rỗng chứ không phải
 * lỗi màn hình. Chỉ normalize đúng 404 có message của ca trực không tồn tại;
 * 404 khác vẫn throw để không che lỗi route/API.
 */
function isEmptyDoctorShiftListError(
  error: unknown,
): boolean {
  if (
    typeof error !== "object" ||
    !error ||
    !("response" in error)
  ) {
    return false;
  }

  const response = (
    error as {
      response?: {
        status?: number;
      };
    }
  ).response;

  if (
    response?.status !== 404
  ) {
    return false;
  }

  const message =
    getDoctorShiftApiErrorMessage(
      error,
    )
      .trim()
      .toLowerCase();

  return message.includes(
    "ca trực bác sĩ không tồn tại",
  );
}

export async function getDoctorShifts(
  params?: GetDoctorShiftsParams,
): Promise<DoctorShiftListResult> {
  try {
    const data =
      await unwrapApiData<DoctorShiftListData>(
        apiClient.get(ENDPOINT, {
          params:
            toListParams(params),
        }),
      );

    return normalizeDoctorShiftListResult(
      data,
      params,
    );
  } catch (error) {
    if (
      !isEmptyDoctorShiftListError(
        error,
      )
    ) {
      throw error;
    }

    return {
      items: [],
      total: 0,
      page:
        params?.page ?? 1,
      limit:
        params?.limit ?? 20,
      totalPages: 0,
    };
  }
}

export async function getAllDoctorShifts(
  params: GetDoctorShiftsParams = {},
): Promise<DoctorShiftItem[]> {
  const limit = Math.max(1, params.limit ?? 100);
  const items: DoctorShiftItem[] = [];
  let page = 1;
  let totalPages = 1;

  do {
    const result = await getDoctorShifts({
      ...params,
      page,
      limit,
    });

    items.push(...result.items);
    totalPages = Math.max(result.totalPages, 1);
    page += 1;
  } while (page <= totalPages);

  return items;
}

export async function getDoctorShift(
  id: string,
): Promise<DoctorShiftItem> {
  const data = await unwrapApiData<BackendDoctorShift>(
    apiClient.get(`${ENDPOINT}/${id}`),
  );

  return normalizeDoctorShift(data);
}

export async function createDoctorShift(
  input: CreateDoctorShiftInput,
): Promise<DoctorShiftApiResponse<DoctorShiftItem>> {
  const response =
    await unwrapApiResponse<BackendDoctorShift>(
      apiClient.post(
        ENDPOINT,
        toCreatePayload(input),
      ),
    );

  return {
    success: response.success ?? true,
    message:
      response.message ?? "Tạo ca trực thành công",
    data: normalizeDoctorShift(response.data),
  };
}

export async function updateDoctorShift(
  id: string,
  input: UpdateDoctorShiftInput,
): Promise<DoctorShiftApiResponse<DoctorShiftItem>> {
  const response =
    await unwrapApiResponse<BackendDoctorShift>(
      apiClient.patch(
        `${ENDPOINT}/${id}`,
        toUpdatePayload(input),
      ),
    );

  return {
    success: response.success ?? true,
    message:
      response.message ??
      "Cập nhật ca trực thành công",
    data: normalizeDoctorShift(response.data),
  };
}

export async function deleteDoctorShift(
  id: string,
  reason: string,
): Promise<DoctorShiftApiResponse<null>> {
  const response = await unwrapApiResponse<null>(
    apiClient.delete(`${ENDPOINT}/${id}`, {
      params: {
        reason: reason.trim(),
      },
    }),
  );

  return {
    success: response.success ?? true,
    message:
      response.message ?? "Xóa ca trực thành công",
    data: response.data ?? null,
  };
}

export function checkDoctorShiftConflicts(
  input: CheckDoctorShiftConflictsInput,
) {
  return unwrapApiData<DoctorShiftConflictResponse>(
    apiClient.post(
      `${ENDPOINT}/check-conflicts`,
      toConflictPayload(input),
    ),
  );
}

export function previewBulkGeneratedShifts(
  input: BulkGenerateDoctorShiftsInput,
) {
  return unwrapApiData<AutoGenerateDoctorShiftsResponse>(
    apiClient.post(
      `${ENDPOINT}/bulk-generate/preview`,
      toBulkGenerateConfirmPayload(input),
    ),
  );
}

export const previewAutoGeneratedShifts =
  previewBulkGeneratedShifts;

export function confirmAutoGeneratedShifts(
  input: BulkGenerateDoctorShiftsInput,
) {
  return unwrapApiData<AutoGenerateDoctorShiftsResponse>(
    apiClient.post(
      `${ENDPOINT}/bulk-generate/confirm`,
      toBulkGenerateConfirmPayload(input),
    ),
  );
}

export function getDoctorAvailability(
  doctorId: string,
  params: GetDoctorAvailabilityParams,
) {
  return unwrapApiData<DoctorAvailabilityResponse>(
    apiClient.get(
      `${ENDPOINT}/availability/doctors/${doctorId}`,
      {
        params: compactObject({
          facilityId: params.facilityId?.trim(),
          date: params.date,
          slotMinutes: params.slotMinutes ?? 30,
        }),
      },
    ),
  );
}

export async function getWeeklyDoctorShifts(
  params?: GetWeeklyDoctorShiftsParams,
): Promise<DoctorShiftItem[]> {
  const data = await unwrapApiData<DoctorShiftListData>(
    apiClient.get(`${ENDPOINT}/weekly`, {
      params: compactObject({
        facilityId: params?.facilityId?.trim(),
        doctorId: params?.doctorId?.trim(),
        weekStart: params?.weekStart,
      }),
    }),
  );

  return normalizeDoctorShiftItems(data);
}

export function getGroupedDoctorShifts(
  params: GetGroupedDoctorShiftsParams,
) {
  return unwrapApiData<BackendGroupedDoctorShifts>(
    apiClient.get(`${ENDPOINT}/grouped`, {
      params: compactObject({
        facilityId: params.facilityId.trim(),
        doctorId: params.doctorId?.trim(),
        roomId: params.roomId?.trim(),
        dateFrom: params.dateFrom,
        dateTo: params.dateTo,
        status: params.status,
        forTemplate: params.forTemplate,
      }),
    }),
  );
}

export function updateWeeklyDoctorShifts(
  input: WeeklyUpdateDoctorShiftsInput,
) {
  return unwrapApiData<WeeklyUpdateDoctorShiftsResponse>(
    apiClient.patch(`${ENDPOINT}/week`, {
      facilityId: input.facilityId.trim(),
      weekStart: input.weekStart,
      shifts: input.shifts.map((shift) => ({
        ...shift,
        shiftId: shift.shiftId?.trim() || undefined,
        staffId: shift.staffId.trim(),
        roleId: shift.roleId?.trim() || undefined,
        roomId:
          shift.status === "off"
            ? null
            : shift.roomId?.trim() || undefined,
        slotId: shift.slotId.trim(),
        note: shift.note?.trim() || undefined,
      })),
      removedShiftIds: input.removedShiftIds,
    }),
  );
}

export const doctorShiftsApi = {
  getDoctorShifts,
  getAllDoctorShifts,
  getDoctorShift,
  createDoctorShift,
  updateDoctorShift,
  deleteDoctorShift,
  checkDoctorShiftConflicts,
  previewBulkGeneratedShifts,
  previewAutoGeneratedShifts,
  confirmAutoGeneratedShifts,
  getDoctorAvailability,
  getWeeklyDoctorShifts,
  getGroupedDoctorShifts,
  updateWeeklyDoctorShifts,
};
