export type DoctorShiftStatus =
  | "available"
  | "full"
  | "cancelled"
  | "off";

export type DoctorShiftWorkingDay =
  | "MON"
  | "TUE"
  | "WED"
  | "THU"
  | "FRI"
  | "SAT"
  | "SUN";

export interface BackendDoctorShift {
  id: string;
  doctorId: unknown;
  staffId: string;
  roleId: unknown;
  slotId: unknown;
  facilityId: string;
  roomId: unknown;
  shiftDate: string;
  startTime: string;
  endTime: string;
  maxAppointments: unknown;
  bookedAppointments?: unknown;
  status: string;
  note?: string | null;
  createdAt: string;
  updatedAt: string;
  staffName?: string | null;
  roleName?: string | null;
  doctorName: string;
  doctorTitle: string;
  doctorSpecialty: string;
  facilityCode: string;
  facilityName: string;
  roomName: unknown;
  roomType: unknown;
  roomTypeId: unknown;
  roomTypeName: unknown;
  slotCode: unknown;
  slotName: unknown;
}

export interface BackendPaginatedDoctorShifts {
  items: BackendDoctorShift[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface DoctorShiftListResult {
  items: DoctorShiftItem[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface DoctorShiftItem {
  id: string;
  doctorId: string;
  staffId: string;
  roleId: string;
  slotId: string;
  facilityId: string;
  roomId: string;
  shiftDate: string;
  startTime: string;
  endTime: string;
  maxAppointments: number;
  bookedAppointments: number;
  status: DoctorShiftStatus;
  note: string;
  createdAt: string;
  updatedAt: string;
  staffName: string;
  roleName: string;
  doctorName: string;
  doctorTitle: string;
  doctorSpecialty: string;
  facilityCode: string;
  facilityName: string;
  roomName: string;
  roomType: string;
  roomTypeId: string;
  roomTypeName: string;
  slotCode: string;
  slotName: string;
}

export interface GetDoctorShiftsParams {
  doctorId?: string;
  facilityId?: string;
  roomId?: string;
  dateFrom?: string;
  dateTo?: string;
  status?: DoctorShiftStatus;
  page?: number;
  limit?: number;
}

export interface CreateDoctorShiftInput {
  doctorId: string;
  staffId: string;
  roleId: string;
  facilityId: string;
  roomId: string;
  slotId: string;
  shiftDate: string;
  maxAppointments: number;
  status: Extract<
    DoctorShiftStatus,
    "available" | "off"
  >;
  note: string;
}

export interface UpdateDoctorShiftInput {
  doctorId?: string;
  staffId?: string;
  roleId?: string;
  facilityId?: string;
  roomId?: string | null;
  slotId?: string | null;
  shiftDate?: string;
  maxAppointments?: number;
  status?: DoctorShiftStatus;
  note?: string;
}

export interface CheckDoctorShiftConflictsInput {
  doctorId: string;
  staffId: string;
  roleId: string;
  facilityId: string;
  roomId: string;
  slotId: string;
  shiftDate: string;
  note: string;
  excludeShiftId?: string;
}

export interface AutoGenerateShiftAssignment {
  staffId: string;
  roleId: string;
  roomId: string;
  workingDays: DoctorShiftWorkingDay[];
  maxAppointments: number;
  status: DoctorShiftStatus;
}

export interface AutoGenerateSlotAssignment {
  slotId: string;
  assignments: AutoGenerateShiftAssignment[];
}

export interface AutoGenerateDoctorShiftsInput {
  facilityId: string;
  fromDate: string;
  toDate?: string;
  durationDays?: number;
  slotAssignments: AutoGenerateSlotAssignment[];
  saveOnlyValid: boolean;
}

export interface BulkGenerateDoctorShiftsInput {
  facilityId: string;
  fromDate: string;
  toDate: string;
  slotAssignments: AutoGenerateSlotAssignment[];
  saveOnlyValid: boolean;
}

export interface WeeklyUpdateShiftInput {
  shiftId?: string;
  staffId: string;
  roleId?: string | null;
  roomId?: string | null;
  slotId: string;
  shiftDate: string;
  maxAppointments?: number | null;
  status: Extract<DoctorShiftStatus, "available" | "off">;
  note?: string;
}

export interface WeeklyUpdateDoctorShiftsInput {
  facilityId: string;
  weekStart: string;
  shifts: WeeklyUpdateShiftInput[];
  removedShiftIds: string[];
}

export interface WeeklyUpdateBlockedItem {
  index: number;
  action: "create" | "update" | "remove";
  shiftId?: string;
  shiftDate?: string;
  reason: string;
}

export interface WeeklyUpdateDoctorShiftsResponse {
  created: BackendDoctorShift[];
  updated: BackendDoctorShift[];
  unchanged: BackendDoctorShift[];
  removedShiftIds: string[];
  blocked: WeeklyUpdateBlockedItem[];
  summary: {
    created: number;
    updated: number;
    unchanged: number;
    removed: number;
    blocked: number;
  };
}

export interface GetDoctorAvailabilityParams {
  facilityId?: string;
  date: string;
  slotMinutes?: number;
}

export interface GetWeeklyDoctorShiftsParams {
  facilityId?: string;
  doctorId?: string;
  weekStart?: string;
}

export interface GetGroupedDoctorShiftsParams {
  facilityId: string;
  doctorId?: string;
  roomId?: string;
  dateFrom: string;
  dateTo: string;
  status?: DoctorShiftStatus;
}

export interface BackendDoctorShiftGroup {
  groupIndex: number;
  workingDays: DoctorShiftWorkingDay[];
  shifts: Array<BackendDoctorShift & { workingDay?: DoctorShiftWorkingDay }>;
}

export interface BackendGroupedDoctorShifts {
  facilityId: string;
  dateFrom: string;
  dateTo: string;
  totalShifts: number;
  totalGroups: number;
  groups: BackendDoctorShiftGroup[];
}

export interface DoctorShiftApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}

export type DoctorShiftConflictResponse = unknown;
export type AutoGenerateDoctorShiftsResponse = unknown;
export type DoctorAvailabilityResponse = unknown;
