export type DoctorShiftStatus =
  | "available"
  | "full"
  | "cancelled"
  | "off";

export type DoctorShiftWorkingDay =
  | "MON"
  | "TUE"
  | "WED"
  | "THU"
  | "FRI"
  | "SAT"
  | "SUN";

/**
 * Dữ liệu nguyên bản trả về từ Management - Shifts.
 * Những field có schema `{}` được giữ là unknown và chuẩn hóa tại API layer.
 */
export interface BackendDoctorShift {
  id: string;
  doctorId: string;
  staffId: string;
  slotId: unknown;
  facilityId: string;
  roomId: unknown;
  shiftDate: string;
  startTime: string;
  endTime: string;
  maxAppointments: unknown;
  status: string;
  note: string | null;
  createdAt: string;
  updatedAt: string;
  doctorName: string;
  doctorTitle: string;
  doctorSpecialty: string;
  facilityCode: string;
  facilityName: string;
  roomName: unknown;
  roomType: unknown;
  roomTypeId: unknown;
  roomTypeName: unknown;
  slotCode: unknown;
  slotName: unknown;
}

export interface BackendPaginatedDoctorShifts {
  items: BackendDoctorShift[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface DoctorShiftListResult {
  items: DoctorShiftItem[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Dữ liệu ca trực sau khi chuẩn hóa để dùng trong giao diện.
 * Chỉ gồm các field có trong response Swagger.
 */
export interface DoctorShiftItem {
  id: string;
  doctorId: string;
  staffId: string;
  slotId: string;
  facilityId: string;
  roomId: string;
  shiftDate: string;
  startTime: string;
  endTime: string;
  maxAppointments: number;
  status: DoctorShiftStatus;
  note: string;
  createdAt: string;
  updatedAt: string;
  doctorName: string;
  doctorTitle: string;
  doctorSpecialty: string;
  facilityCode: string;
  facilityName: string;
  roomName: string;
  roomType: string;
  roomTypeId: string;
  roomTypeName: string;
  slotCode: string;
  slotName: string;
}

export interface GetDoctorShiftsParams {
  doctorId?: string;
  facilityId?: string;
  roomId?: string;
  dateFrom?: string;
  dateTo?: string;
  status?: DoctorShiftStatus;
  page?: number;
  limit?: number;
}

export interface CreateDoctorShiftInput {
  doctorId: string;
  facilityId: string;
  roomId: string;
  slotId: string;
  shiftDate: string;
  maxAppointments: number;
  status: Extract<
    DoctorShiftStatus,
    "available" | "off"
  >;
  note: string;
}

export interface UpdateDoctorShiftInput {
  doctorId?: string;
  facilityId?: string;
  roomId?: string;
  slotId?: string;
  shiftDate?: string;
  maxAppointments?: number;
  status?: DoctorShiftStatus;
  note?: string;
}

export interface CheckDoctorShiftConflictsInput {
  doctorId: string;
  facilityId: string;
  roomId: string;
  slotId: string;
  shiftDate: string;
  excludeShiftId?: string;
}

export interface AutoGenerateDoctorShiftsInput {
  doctorId: string;
  facilityId: string;
  roomId: string;
  slotId: string | number;
  fromDate?: string;
  toDate?: string;
  durationDays?: number;
  workingDays: DoctorShiftWorkingDay[];
  maxAppointments: number;
  status: DoctorShiftStatus;
  saveOnlyValid: boolean;
}

export interface GetDoctorAvailabilityParams {
  facilityId?: string;
  date: string;
  slotMinutes?: number;
}

export interface GetWeeklyDoctorShiftsParams {
  facilityId?: string;
  doctorId?: string;
  weekStart?: string;
}

export interface DoctorShiftApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}

export type DoctorShiftConflictResponse = unknown;
export type AutoGenerateDoctorShiftsResponse = unknown;
export type DoctorAvailabilityResponse = unknown;