import {
  apiClient,
  unwrapApiData,
  unwrapApiResponse,
} from "@/lib/axios";
import type {
  AutoGenerateDoctorShiftsInput,
  AutoGenerateDoctorShiftsResponse,
  BackendDoctorShift,
  BackendPaginatedDoctorShifts,
  CheckDoctorShiftConflictsInput,
  CreateDoctorShiftInput,
  DoctorAvailabilityResponse,
  DoctorShiftApiResponse,
  DoctorShiftConflictResponse,
  DoctorShiftItem,
  DoctorShiftStatus,
  GetDoctorAvailabilityParams,
  GetDoctorShiftsParams,
  GetWeeklyDoctorShiftsParams,
  UpdateDoctorShiftInput,
} from "./doctor-shifts.types";

const ENDPOINT = "/management/shifts";

function compactObject(
  value: Record<string, unknown>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value).filter(
      ([, item]) =>
        item !== undefined &&
        item !== null &&
        item !== "",
    ),
  );
}

function toStringValue(value: unknown): string {
  if (value === undefined || value === null) {
    return "";
  }

  return String(value).trim();
}

function toNumberValue(value: unknown): number {
  const parsed = Number(value);

  return Number.isFinite(parsed) && parsed >= 0
    ? parsed
    : 0;
}

function normalizeTime(value: string): string {
  const [hour = "00", minute = "00"] = String(
    value ?? "",
  )
    .trim()
    .split(":");

  return `${hour.padStart(2, "0")}:${minute.padStart(
    2,
    "0",
  )}`;
}

function normalizeStatus(
  status: string,
): DoctorShiftStatus {
  const normalized = String(status ?? "")
    .trim()
    .toLowerCase();

  if (
    normalized === "available" ||
    normalized === "full" ||
    normalized === "cancelled" ||
    normalized === "off"
  ) {
    return normalized;
  }

  return "available";
}

function normalizeDoctorShift(
  shift: BackendDoctorShift,
): DoctorShiftItem {
  return {
    id: toStringValue(shift.id),
    doctorId: toStringValue(shift.doctorId),
    staffId: toStringValue(shift.staffId),
    slotId: toStringValue(shift.slotId),
    facilityId: toStringValue(shift.facilityId),
    roomId: toStringValue(shift.roomId),
    shiftDate: toStringValue(shift.shiftDate),
    startTime: normalizeTime(shift.startTime),
    endTime: normalizeTime(shift.endTime),
    maxAppointments: toNumberValue(
      shift.maxAppointments,
    ),
    status: normalizeStatus(shift.status),
    note: toStringValue(shift.note),
    createdAt: toStringValue(shift.createdAt),
    updatedAt: toStringValue(shift.updatedAt),
    doctorName: toStringValue(shift.doctorName),
    doctorTitle: toStringValue(shift.doctorTitle),
    doctorSpecialty: toStringValue(
      shift.doctorSpecialty,
    ),
    facilityCode: toStringValue(
      shift.facilityCode,
    ),
    facilityName: toStringValue(
      shift.facilityName,
    ),
    roomName: toStringValue(shift.roomName),
    roomType: toStringValue(shift.roomType),
    roomTypeId: toStringValue(shift.roomTypeId),
    roomTypeName: toStringValue(
      shift.roomTypeName,
    ),
    slotCode: toStringValue(shift.slotCode),
    slotName: toStringValue(shift.slotName),
  };
}

type DoctorShiftListData =
  | BackendDoctorShift[]
  | BackendPaginatedDoctorShifts
  | {
      days?: Array<{
        date?: string;
        shifts?: BackendDoctorShift[];
      }>;
    };

function normalizeDoctorShiftList(
  data: DoctorShiftListData,
): DoctorShiftItem[] {
  if (Array.isArray(data)) {
    return data.map(normalizeDoctorShift);
  }

  if ("days" in data && Array.isArray(data.days)) {
    return data.days.flatMap((day) => {
      if (!Array.isArray(day.shifts)) {
        return [];
      }

      return day.shifts.map((shift) =>
        normalizeDoctorShift({
          ...shift,
          shiftDate: shift.shiftDate || day.date || "",
        }),
      );
    });
  }

  return "items" in data && Array.isArray(data.items)
    ? data.items.map(normalizeDoctorShift)
    : [];
}

function toListParams(
  params?: GetDoctorShiftsParams,
): Record<string, unknown> {
  return compactObject({
    doctorId: params?.doctorId?.trim(),
    facilityId: params?.facilityId?.trim(),
    roomId: params?.roomId?.trim(),
    dateFrom: params?.dateFrom,
    dateTo: params?.dateTo,
    status: params?.status,
    page: params?.page,
    limit: params?.limit ?? 20,
  });
}

function toCreatePayload(
  input: CreateDoctorShiftInput,
): Record<string, unknown> {
  return {
    doctorId: input.doctorId.trim(),
    facilityId: input.facilityId.trim(),
    roomId: input.roomId.trim(),
    slotId: input.slotId.trim(),
    shiftDate: input.shiftDate,
    maxAppointments: input.maxAppointments,
    status: input.status,
    note: input.note.trim(),
  };
}

function toUpdatePayload(
  input: UpdateDoctorShiftInput,
): Record<string, unknown> {
  return compactObject({
    doctorId: input.doctorId?.trim(),
    facilityId: input.facilityId?.trim(),
    roomId: input.roomId?.trim(),
    slotId: input.slotId?.trim(),
    shiftDate: input.shiftDate,
    maxAppointments: input.maxAppointments,
    status: input.status,
    note: input.note?.trim(),
  });
}

function toConflictPayload(
  input: CheckDoctorShiftConflictsInput,
): Record<string, unknown> {
  return compactObject({
    doctorId: input.doctorId.trim(),
    facilityId: input.facilityId.trim(),
    roomId: input.roomId.trim(),
    slotId: input.slotId.trim(),
    shiftDate: input.shiftDate,
    excludeShiftId: input.excludeShiftId?.trim(),
  });
}

function toAutoGeneratePayload(
  input: AutoGenerateDoctorShiftsInput,
): Record<string, unknown> {
  return compactObject({
    doctorId: input.doctorId.trim(),
    facilityId: input.facilityId.trim(),
    roomId: input.roomId.trim(),
    slotId: input.slotId,
    fromDate: input.fromDate,
    toDate: input.toDate,
    durationDays: input.durationDays,
    workingDays: input.workingDays,
    maxAppointments: input.maxAppointments,
    status: input.status,
    saveOnlyValid: input.saveOnlyValid,
  });
}

export async function getDoctorShifts(
  params?: GetDoctorShiftsParams,
): Promise<DoctorShiftItem[]> {
  const data = await unwrapApiData<DoctorShiftListData>(
    apiClient.get(ENDPOINT, {
      params: toListParams(params),
    }),
  );

  return normalizeDoctorShiftList(data);
}

export async function getDoctorShift(
  id: string,
): Promise<DoctorShiftItem> {
  const data = await unwrapApiData<BackendDoctorShift>(
    apiClient.get(`${ENDPOINT}/${id}`),
  );

  return normalizeDoctorShift(data);
}

export async function createDoctorShift(
  input: CreateDoctorShiftInput,
): Promise<DoctorShiftApiResponse<DoctorShiftItem>> {
  const response =
    await unwrapApiResponse<BackendDoctorShift>(
      apiClient.post(
        ENDPOINT,
        toCreatePayload(input),
      ),
    );

  return {
    success: response.success ?? true,
    message:
      response.message ?? "Tạo ca trực thành công",
    data: normalizeDoctorShift(response.data),
  };
}

export async function updateDoctorShift(
  id: string,
  input: UpdateDoctorShiftInput,
): Promise<DoctorShiftApiResponse<DoctorShiftItem>> {
  const response =
    await unwrapApiResponse<BackendDoctorShift>(
      apiClient.patch(
        `${ENDPOINT}/${id}`,
        toUpdatePayload(input),
      ),
    );

  return {
    success: response.success ?? true,
    message:
      response.message ??
      "Cập nhật ca trực thành công",
    data: normalizeDoctorShift(response.data),
  };
}

export async function deleteDoctorShift(
  id: string,
  reason: string,
): Promise<DoctorShiftApiResponse<null>> {
  const response = await unwrapApiResponse<null>(
    apiClient.delete(`${ENDPOINT}/${id}`, {
      params: {
        reason: reason.trim(),
      },
    }),
  );

  return {
    success: response.success ?? true,
    message:
      response.message ?? "Xóa ca trực thành công",
    data: response.data ?? null,
  };
}

export function checkDoctorShiftConflicts(
  input: CheckDoctorShiftConflictsInput,
) {
  return unwrapApiData<DoctorShiftConflictResponse>(
    apiClient.post(
      `${ENDPOINT}/check-conflicts`,
      toConflictPayload(input),
    ),
  );
}

export function previewAutoGeneratedShifts(
  input: AutoGenerateDoctorShiftsInput,
) {
  return unwrapApiData<AutoGenerateDoctorShiftsResponse>(
    apiClient.post(
      `${ENDPOINT}/auto-generate/preview`,
      toAutoGeneratePayload(input),
    ),
  );
}

export function confirmAutoGeneratedShifts(
  input: AutoGenerateDoctorShiftsInput,
) {
  return unwrapApiData<AutoGenerateDoctorShiftsResponse>(
    apiClient.post(
      `${ENDPOINT}/auto-generate/confirm`,
      toAutoGeneratePayload(input),
    ),
  );
}

export function getDoctorAvailability(
  doctorId: string,
  params: GetDoctorAvailabilityParams,
) {
  return unwrapApiData<DoctorAvailabilityResponse>(
    apiClient.get(
      `${ENDPOINT}/availability/doctors/${doctorId}`,
      {
        params: compactObject({
          facilityId: params.facilityId?.trim(),
          date: params.date,
          slotMinutes: params.slotMinutes ?? 30,
        }),
      },
    ),
  );
}

export async function getWeeklyDoctorShifts(
  params?: GetWeeklyDoctorShiftsParams,
): Promise<DoctorShiftItem[]> {
  const data = await unwrapApiData<DoctorShiftListData>(
    apiClient.get(`${ENDPOINT}/weekly`, {
      params: compactObject({
        facilityId: params?.facilityId?.trim(),
        doctorId: params?.doctorId?.trim(),
        weekStart: params?.weekStart,
      }),
    }),
  );

  return normalizeDoctorShiftList(data);
}

export const doctorShiftsApi = {
  getDoctorShifts,
  getDoctorShift,
  createDoctorShift,
  updateDoctorShift,
  deleteDoctorShift,
  checkDoctorShiftConflicts,
  previewAutoGeneratedShifts,
  confirmAutoGeneratedShifts,
  getDoctorAvailability,
  getWeeklyDoctorShifts,
};
