"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Alert,
  App,
  Button,
  Col,
  Form,
  Input,
  Modal,
  Row,
  Select,
  Tag,
  Typography,
} from "antd";
import {
  Calendar,
  Clock,
  Copy,
  Eye,
  X,
} from "lucide-react";
import {
  confirmAutoGeneratedShifts,
  getGroupedDoctorShifts,
  previewBulkGeneratedShifts,
} from "@/management/features/doctor-shifts/doctor-shifts.api";
import type {
  BulkGenerateDoctorShiftsInput,
} from "@/management/features/doctor-shifts/doctor-shifts.types";
import { getShiftSlotLookup } from "@/management/features/shift-slots/shift-slots.api";
import type { ShiftSlotLookupItem } from "@/management/features/shift-slots/shift-slots.types";
import {
  addDaysToDateKey,
  formatIssueDate,
  formatLockedWeekDate,
  getCurrentWeekDateRange,
  getNextWeekMondayDateKey,
  isNextWeekMondayDateKey,
} from "@/management/features/doctor-shifts/doctor-shifts.weekly-utils";
import {
  isRecord,
} from "@/management/features/doctor-shifts/doctor-shifts.utils";
import {
  getResponseMessage,
  readBulkGenerationResult,
} from "@/management/features/doctor-shifts/doctor-shifts.bulk-result";
import type {
  BulkGenerationResult,
} from "@/management/features/doctor-shifts/doctor-shifts.bulk-result";
import {
  DoctorShiftWeeklyAssignments,
} from "./DoctorShiftWeeklyAssignments";
import {
  useDoctorShiftBulkIssues,
} from "@/hooks/doctor-shifts/useDoctorShiftBulkIssues";
import {
  buildBulkGeneratePayload,
} from "@/management/features/doctor-shifts/doctor-shifts.bulk-payload";
import {
  buildImportedWeekSlotGroups,
} from "@/management/features/doctor-shifts/doctor-shifts.import-week";
import {
  clearWeeklyDraft,
  mergeDraftSlotGroups,
  readWeeklyDraft,
  saveWeeklyDraft,
} from "@/management/features/doctor-shifts/doctor-shifts.bulk-draft";
import type {
  BulkGenerateFormValues,
} from "@/management/features/doctor-shifts/doctor-shifts.bulk-draft";
import {
  getErrorMessage,
} from "./doctor-shift-modal.shared";
import type {
  DoctorOption,
  FacilityOption,
  RoomOption,
} from "./doctor-shift-modal.shared";
import {
  DoctorShiftBulkPreviewModal,
} from "./DoctorShiftBulkPreviewModal";

const { Text, Title } = Typography;

type DoctorShiftBulkGenerateModalProps = {
  open: boolean;
  facilities: FacilityOption[];
  rooms: RoomOption[];
  doctors: DoctorOption[];
  onClose: () => void;
  onGenerated: (range: {
    fromDate: string;
    toDate: string;
  }) => Promise<void> | void;
};

type LockedWeekDateInputProps = {
  value?: string;
};

function LockedWeekDateInput({
  value,
}: LockedWeekDateInputProps) {
  return (
    <Input
      value={formatLockedWeekDate(
        value,
      )}
      readOnly
      disabled
    />
  );
}

export function DoctorShiftBulkGenerateModal({
  open,
  facilities,
  rooms,
  doctors,
  onClose,
  onGenerated,
}: DoctorShiftBulkGenerateModalProps) {
  const { message: messageApi } = App.useApp();
  const [form] =
    Form.useForm<BulkGenerateFormValues>();
  const [shiftSlots, setShiftSlots] = useState<
    ShiftSlotLookupItem[]
  >([]);
  const [slotsLoading, setSlotsLoading] =
    useState(false);
  const [previewLoading, setPreviewLoading] =
    useState(false);
  const [importWeekLoading, setImportWeekLoading] =
    useState(false);
  const [confirmLoading, setConfirmLoading] =
    useState(false);
  const [previewModalOpen, setPreviewModalOpen] =
    useState(false);
  const [previewPayload, setPreviewPayload] =
    useState<BulkGenerateDoctorShiftsInput | null>(
      null,
    );
  const [previewValues, setPreviewValues] =
    useState<BulkGenerateFormValues | null>(
      null,
    );
  const [previewResult, setPreviewResult] =
    useState<BulkGenerationResult | null>(
      null,
    );
  const [error, setError] = useState<
    string | null
  >(null);
  const pendingDraftRef = useRef<
    BulkGenerateFormValues | null
  >(null);

  const watchedFacilityId =
    Form.useWatch("facilityId", form) ?? "";
  const watchedFromDate =
    Form.useWatch("fromDate", form) ?? "";
  const watchedSlotGroups =
    Form.useWatch("slotGroups", form) ?? [];

  const slotById = useMemo(
    () =>
      new Map(
        shiftSlots.map((slot) => [slot.id, slot]),
      ),
    [shiftSlots],
  );

  const {
    generationIssues,
    setGenerationIssues,
    hasFieldIssues,
    clearIssues,
    clearIssueFields,
    applyIssues,
  } = useDoctorShiftBulkIssues({
    form,
    slotById,
    doctors,
    rooms,
  });

  const previewCanConfirm =
    Boolean(
      previewResult &&
      previewResult.recognized &&
      previewResult.valid > 0,
    );

  const roomOptions = useMemo(
    () =>
      rooms
        .filter(
          (room) =>
            room.facilityId === watchedFacilityId,
        )
        .map((room) => ({
          value: room.id,
          label: `${room.name}${
            room.floor
              ? ` · ${room.floor}`
              : ""
          }`,
        })),
    [rooms, watchedFacilityId],
  );

  const doctorOptions = useMemo(
    () =>
      doctors
        .filter(
          (doctor) =>
            doctor.status === "active" &&
            doctor.staffId &&
            doctor.roleId &&
            doctor.facilityIds.includes(
              watchedFacilityId,
            ),
        )
        .map((doctor) => ({
          value: doctor.staffId,
          label: `${doctor.title} ${doctor.name} · ${doctor.specialty}`,
        })),
    [doctors, watchedFacilityId],
  );

  useEffect(() => {
    if (!open) return;

    const nextWeekMonday =
      getNextWeekMondayDateKey();
    const defaultFacilityId =
      facilities.length === 1
        ? facilities[0]?.id
        : undefined;
    const restoredDraft =
      defaultFacilityId
        ? readWeeklyDraft(
            defaultFacilityId,
            nextWeekMonday,
          )
        : null;

    const timer = window.setTimeout(() => {
      pendingDraftRef.current =
        restoredDraft;

      form.resetFields();
      form.setFieldsValue({
        facilityId:
          defaultFacilityId,
        fromDate:
          nextWeekMonday,
        slotGroups: [],
      });
      setShiftSlots([]);
      setError(null);
      setGenerationIssues([]);
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);
      clearIssueFields();
    }, 0);

    return () => {
      window.clearTimeout(timer);
    };
  }, [
    clearIssueFields,
    facilities,
    form,
    open,
    setGenerationIssues,
  ]);

  useEffect(() => {
    if (!open || !watchedFacilityId) {
      return;
    }

    let cancelled = false;

    void Promise.resolve()
      .then(() => {
        if (!cancelled) {
          setSlotsLoading(true);
        }

        return getShiftSlotLookup({
          facilityId: watchedFacilityId,
          status: "active",
        });
      })
      .then((slots) => {
        if (cancelled) return;

        setShiftSlots(slots);

        const restoredDraft =
          pendingDraftRef.current;
        const slotGroups =
          mergeDraftSlotGroups(
            slots,
            restoredDraft,
          );

        form.setFieldsValue({
          slotGroups,
        });

        pendingDraftRef.current =
          null;
      })
      .catch((loadError) => {
        if (cancelled) return;

        setShiftSlots([]);
        pendingDraftRef.current =
          null;
        form.setFieldsValue({
          slotGroups: [],
        });
        setError(getErrorMessage(loadError));
      })
      .finally(() => {
        if (!cancelled) {
          setSlotsLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [
    form,
    open,
    watchedFacilityId,
  ]);

  async function handleImportCurrentWeek() {
    setError(null);
    clearIssues();

    if (!watchedFacilityId) {
      const message =
        "Vui lòng chọn cơ sở trước khi lấy lịch tuần này.";
      setError(message);
      messageApi.warning(message);
      return;
    }

    const { dateFrom, dateTo } = getCurrentWeekDateRange();
    setImportWeekLoading(true);

    try {
      const schedule = await getGroupedDoctorShifts({
        facilityId: watchedFacilityId,
        dateFrom,
        dateTo,
        forTemplate: true,
      });

      const {
        slotGroups,
        importedAssignments,
        skippedGroups,
      } = buildImportedWeekSlotGroups({
        schedule,
        shiftSlots,
        rooms,
        doctors,
        facilityId: watchedFacilityId,
      });

      if (importedAssignments === 0) {
        const message =
          `Không có lịch phù hợp để lấy từ tuần ${formatIssueDate(dateFrom)} - ${formatIssueDate(dateTo)}.`;
        setError(message);
        messageApi.warning(message);
        return;
      }

      const nextValues: BulkGenerateFormValues = {
        facilityId: watchedFacilityId,
        fromDate: watchedFromDate || getNextWeekMondayDateKey(),
        slotGroups,
      };

      form.setFieldsValue(nextValues);
      saveWeeklyDraft(nextValues);
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);

      const skippedMessage =
        skippedGroups > 0
          ? ` Bỏ qua ${skippedGroups} nhóm có bác sĩ hoặc khung ca không còn hợp lệ.`
          : "";

      messageApi.success(
        `Đã lấy ${importedAssignments} phân công từ tuần ${formatIssueDate(dateFrom)} - ${formatIssueDate(dateTo)}.${skippedMessage}`,
      );
    } catch (importError) {
      const message = getErrorMessage(importError);
      setError(message);
      messageApi.error(message);
    } finally {
      setImportWeekLoading(false);
    }
  }

  async function handlePreview() {
    setError(null);
    setGenerationIssues([]);
    clearIssueFields();

    try {
      const values =
        await form.validateFields();
      const payload = buildBulkGeneratePayload(values, doctors, shiftSlots);

      setPreviewLoading(true);

      const response =
        await previewBulkGeneratedShifts(
          payload,
        );
      const result =
        readBulkGenerationResult(
          response,
        );

      if (!result.recognized) {
        throw new Error(
          "Không đọc được kết quả xem trước từ hệ thống.",
        );
      }

      const hasIssues =
        result.skipped > 0 ||
        result.conflicted > 0 ||
        result.canConfirm === false ||
        result.allOrNothingRejected;

      if (hasIssues) {
        applyIssues(
          result,
          values,
        );
      } else {
        setGenerationIssues([]);
      }

      setPreviewPayload(payload);
      setPreviewValues(values);
      setPreviewResult(result);
      setPreviewModalOpen(true);
    } catch (previewError) {
      const message =
        getErrorMessage(previewError);

      setError(message);

      if (
        !(
          isRecord(previewError) &&
          "errorFields" in previewError
        )
      ) {
        messageApi.error(message);
      }
    } finally {
      setPreviewLoading(false);
    }
  }

  async function handleConfirmPreview() {
    if (
      !previewPayload ||
      !previewValues ||
      !previewResult ||
      !previewCanConfirm
    ) {
      return;
    }

    setConfirmLoading(true);
    setError(null);

    try {
      const response =
        await confirmAutoGeneratedShifts(
          previewPayload,
        );
      const result =
        readBulkGenerationResult(
          response,
        );

      const createdCount =
        result.createdCount;

      if (
        result.recognized &&
        createdCount === 0
      ) {
        const issues =
          applyIssues(
            result,
            previewValues,
          );

        setPreviewResult(result);

        const summaryMessage =
          "Không có ca trực hợp lệ nào được tạo.";

        setError(summaryMessage);
        setGenerationIssues(issues);
        messageApi.error(
          summaryMessage,
        );
        return;
      }

      await onGenerated({
        fromDate:
          previewPayload.fromDate,
        toDate: previewPayload.toDate,
      });

      messageApi.success(
        getResponseMessage(
          response,
          result.recognized &&
          result.createdCount > 0
            ? (
                result.skipped > 0 ||
                result.conflicted > 0
                  ? `Đã tạo ${result.createdCount} ca trực hợp lệ. Các ca bị trùng hoặc bị bỏ qua không được tạo.`
                  : `Tạo thành công ${result.createdCount} ca trực.`
              )
            : "Tạo lịch trực 1 tuần thành công.",
        ),
      );

      clearWeeklyDraft(
        previewPayload.facilityId,
      );
      pendingDraftRef.current =
        null;
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);
      setGenerationIssues([]);
      form.resetFields();
      onClose();
    } catch (confirmError) {
      const message =
        getErrorMessage(confirmError);

      setError(message);
      messageApi.error(message);
    } finally {
      setConfirmLoading(false);
    }
  }

  function handleCancel() {
    if (
      previewLoading ||
      confirmLoading
    ) {
      return;
    }

    const currentValues =
      form.getFieldsValue(
        true,
      );

    saveWeeklyDraft(
      currentValues,
    );

    clearIssueFields();
    setError(null);
    setGenerationIssues([]);
    setPreviewModalOpen(false);
    setPreviewPayload(null);
    setPreviewValues(null);
    setPreviewResult(null);
    onClose();
  }

  return (
    <>
      <Modal
      open={open}
      centered
      width={1120}
      title={null}
      footer={null}
      closable={false}
      onCancel={handleCancel}
      mask={{
        closable:
          !previewLoading &&
          !confirmLoading,
      }}
      destroyOnHidden
      styles={{
        body: {
          maxHeight: "82vh",
          overflow: "hidden",
        },
      }}
    >
      <div className="relative mb-5 border-b border-slate-200 pb-4 pr-12">
        <button
          type="button"
          aria-label="Đóng"
          disabled={
            previewLoading ||
            confirmLoading
          }
          onClick={handleCancel}
          className="absolute right-0 top-0 z-10 flex h-9 w-9 items-center justify-center rounded-full text-slate-400 transition hover:bg-slate-100 hover:text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-start gap-3">
          <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-white">
            <Calendar className="h-5 w-5" />
          </span>

          <div>
            <Title
              level={4}
              className="!mb-1 !text-slate-950"
            >
              Tạo lịch trực 1 tuần
            </Title>

            <Text type="secondary">
              Phân công bác sĩ theo từng khung ca, phòng và ngày làm việc. Hệ thống chỉ tạo lịch cho tuần kế tiếp, từ Thứ 2 đến Chủ nhật.
            </Text>

            <Text
              type="secondary"
              className="mt-1 block text-xs"
            >
              Bản nháp được tự động lưu và sẽ được khôi phục khi mở lại.
            </Text>
          </div>
        </div>
      </div>

      <div
        className="pr-3"
        style={{
          maxHeight: "calc(82vh - 180px)",
          overflowY: "auto",
          scrollbarGutter: "stable",
        }}
      >
        {error ? (
          <Alert
            type="error"
            title={error}
            showIcon
            closable
            className="mb-4"
            onClose={() =>
              setError(null)
            }
          />
        ) : null}

      <Form<BulkGenerateFormValues>
        form={form}
        layout="vertical"
        requiredMark="optional"
        onValuesChange={(
          changedValues,
          allValues,
        ) => {
          if (
            generationIssues.length >
              0 ||
            hasFieldIssues()
          ) {
            clearIssueFields();
            setGenerationIssues([]);
            setError(null);
          }

          setPreviewModalOpen(false);
          setPreviewPayload(null);
          setPreviewValues(null);
          setPreviewResult(null);

          if (
            "facilityId" in
            changedValues
          ) {
            const facilityId =
              changedValues.facilityId as string;

            setShiftSlots([]);
            setSlotsLoading(
              Boolean(facilityId),
            );
            form.setFieldsValue({
              slotGroups: [],
            });
          }

          saveWeeklyDraft(
            allValues,
          );
        }}
      >
        <Row gutter={[16, 0]}>
          <Col xs={24} lg={12}>
            <Form.Item
              name="facilityId"
              label="Cơ sở"
              rules={[
                {
                  required: true,
                  message:
                    "Vui lòng chọn cơ sở.",
                },
              ]}
            >
              <Select
                showSearch
                optionFilterProp="label"
                disabled={
                  facilities.length === 1
                }
                placeholder="Chọn cơ sở khám"
                options={facilities.map(
                  (facility) => ({
                    value: facility.id,
                    label: `${facility.name} (${facility.code})`,
                  }),
                )}
              />
            </Form.Item>
          </Col>

          <Col xs={24} lg={12}>
            <Form.Item
              name="fromDate"
              label="Tuần được xếp lịch"
              extra={
                watchedFromDate
                  ? `Từ Thứ 2 ${formatIssueDate(
                      watchedFromDate,
                    )} đến Chủ nhật ${formatIssueDate(
                      addDaysToDateKey(
                        watchedFromDate,
                        6,
                      ),
                    )}.`
                  : "Hệ thống tự xác định tuần kế tiếp."
              }
              rules={[
                {
                  required: true,
                  message:
                    "Không xác định được tuần kế tiếp.",
                },
                {
                  validator: async (
                    _rule,
                    value?: string,
                  ) => {
                    if (
                      value &&
                      !isNextWeekMondayDateKey(
                        value,
                      )
                    ) {
                      throw new Error(
                        "Chỉ được xếp lịch cho tuần kế tiếp.",
                      );
                    }
                  },
                },
              ]}
            >
              <LockedWeekDateInput />
            </Form.Item>
          </Col>
        </Row>

        <div className="mb-3 flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
          <div>
            <Text
              strong
              className="block text-slate-950"
            >
              Phân công theo khung ca
            </Text>

            <Text
              type="secondary"
              className="text-sm"
            >
              Mỗi bác sĩ chọn phòng, các ngày làm việc trong tuần và số lịch tối đa.
            </Text>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Button
              icon={<Copy className="h-4 w-4" />}
              loading={importWeekLoading}
              disabled={
                !watchedFacilityId ||
                slotsLoading ||
                previewLoading ||
                confirmLoading
              }
              onClick={() =>
                void handleImportCurrentWeek()
              }
            >
              Lấy lịch tuần này
            </Button>

            {watchedFacilityId &&
            !slotsLoading ? (
              <Tag color="blue">
                {shiftSlots.length} khung ca
              </Tag>
            ) : null}
          </div>
        </div>

        {!watchedFacilityId ? (
          <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center">
            <Clock className="mx-auto h-7 w-7 text-slate-400" />

            <Text className="mt-3 block font-medium text-slate-700">
              Vui lòng chọn cơ sở
            </Text>

            <Text
              type="secondary"
              className="mt-1 block text-sm"
            >
              Các khung ca hoạt động của cơ sở sẽ hiển thị tại đây.
            </Text>
          </div>
        ) : slotsLoading ? (
          <div className="rounded-xl border border-slate-200 bg-slate-50 px-5 py-10 text-center">
            <Text type="secondary">
              Đang tải danh sách khung ca...
            </Text>
          </div>
        ) : shiftSlots.length === 0 ? (
          <Alert
            type="warning"
            showIcon
            title="Cơ sở chưa có khung ca hoạt động"
          />
        ) : (
          <DoctorShiftWeeklyAssignments
            form={form}
            shiftSlots={shiftSlots}
            watchedSlotGroups={watchedSlotGroups}
            slotById={slotById}
            doctorOptions={doctorOptions}
            roomOptions={roomOptions}
          />
        )}

      </Form>
      </div>

      <div className="mt-4 flex flex-col-reverse justify-end gap-2 border-t border-slate-200 pt-4 sm:flex-row">
        <Button
          disabled={
            previewLoading ||
            confirmLoading ||
            importWeekLoading
          }
          onClick={handleCancel}
        >
          Hủy
        </Button>

        <Button
          type="primary"
          loading={previewLoading}
          disabled={
            confirmLoading ||
            importWeekLoading
          }
          icon={
            <Eye className="h-4 w-4" />
          }
          onClick={() =>
            void handlePreview()
          }
        >
          Xem trước lịch tuần
        </Button>
      </div>
      </Modal>

      <DoctorShiftBulkPreviewModal
        open={previewModalOpen}
        totalCandidates={
          previewResult?.totalCandidates ??
          0
        }
        valid={previewResult?.valid ?? 0}
        skipped={
          previewResult?.skipped ?? 0
        }
        conflicted={
          previewResult?.conflicted ?? 0
        }
        issues={generationIssues}
        canConfirm={previewCanConfirm}
        confirmLoading={confirmLoading}
        onClose={() => {
          if (!confirmLoading) {
            setPreviewModalOpen(false);
          }
        }}
        onConfirm={
          handleConfirmPreview
        }
      />
    </>
  );
}
