"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Alert,
  App,
  Button,
  Checkbox,
  Col,
  Form,
  Input,
  InputNumber,
  Modal,
  Row,
  Select,
  Tag,
  Typography,
} from "antd";
import {
  Calendar,
  Clock,
  Copy,
  Eye,
  Plus,
  Trash2,
  X,
} from "lucide-react";
import {
  confirmAutoGeneratedShifts,
  getGroupedDoctorShifts,
  previewBulkGeneratedShifts,
} from "@/management/features/doctor-shifts/doctor-shifts.api";
import type {
  BulkGenerateDoctorShiftsInput,
  DoctorShiftStatus,
  DoctorShiftWorkingDay,
} from "@/management/features/doctor-shifts/doctor-shifts.types";
import { getShiftSlotLookup } from "@/management/features/shift-slots/shift-slots.api";
import type { ShiftSlotLookupItem } from "@/management/features/shift-slots/shift-slots.types";
import {
  getErrorMessage,
} from "./doctor-shift-modal.shared";
import type {
  DoctorOption,
  FacilityOption,
  RoomOption,
} from "./doctor-shift-modal.shared";
import {
  DoctorShiftBulkPreviewModal,
} from "./DoctorShiftBulkPreviewModal";

const { Text, Title } = Typography;

const WORKING_DAY_OPTIONS: Array<{
  label: string;
  value: DoctorShiftWorkingDay;
}> = [
  { label: "Thứ 2", value: "MON" },
  { label: "Thứ 3", value: "TUE" },
  { label: "Thứ 4", value: "WED" },
  { label: "Thứ 5", value: "THU" },
  { label: "Thứ 6", value: "FRI" },
  { label: "Thứ 7", value: "SAT" },
  { label: "Chủ nhật", value: "SUN" },
];

const WEEKLY_DRAFT_STORAGE_PREFIX =
  "management-doctor-shifts-weekly-draft:v1";

function getSlotWorkingDayOptions(
  slot?: ShiftSlotLookupItem | null,
) {
  const applicableDays =
    slot?.applicableDays?.length
      ? new Set(slot.applicableDays)
      : null;

  return WORKING_DAY_OPTIONS.filter(
    (option) =>
      !applicableDays ||
      applicableDays.has(option.value),
  );
}

function getDefaultWorkingDays(
  slot?: ShiftSlotLookupItem | null,
): DoctorShiftWorkingDay[] {
  const slotDays = getSlotWorkingDayOptions(slot).map(
    (option) => option.value,
  );

  return slotDays.length > 0
    ? slotDays
    : ["MON", "TUE", "WED", "THU", "FRI"];
}

type BulkAssignmentFormValue = {
  staffId: string;
  roomId: string;
  workingDays: DoctorShiftWorkingDay[];
  maxAppointments: number;
  status: Extract<
    DoctorShiftStatus,
    "available" | "off"
  >;
};

type BulkSlotGroupFormValue = {
  slotId: string;
  assignments: BulkAssignmentFormValue[];
};

type BulkGenerateFormValues = {
  facilityId: string;
  fromDate: string;
  slotGroups: BulkSlotGroupFormValue[];
};

type BulkGenerateDraft = {
  version: 1;
  savedAt: string;
  values: BulkGenerateFormValues;
};

type BulkGenerationIssueFieldPath =
  | [
      "slotGroups",
      number,
      "assignments",
      number,
      "staffId",
    ]
  | [
      "slotGroups",
      number,
      "assignments",
      number,
      "roomId",
    ];

type DoctorShiftBulkGenerateModalProps = {
  open: boolean;
  facilities: FacilityOption[];
  rooms: RoomOption[];
  doctors: DoctorOption[];
  onClose: () => void;
  onGenerated: (range: {
    fromDate: string;
    toDate: string;
  }) => Promise<void> | void;
};

function toDateKey(date: Date) {
  const year = date.getFullYear();
  const month = String(
    date.getMonth() + 1,
  ).padStart(2, "0");
  const day = String(
    date.getDate(),
  ).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function getNextWeekMondayDateKey() {
  const currentDate = new Date();
  const currentDay =
    currentDate.getDay();
  const daysUntilNextMonday =
    currentDay === 0
      ? 1
      : 8 - currentDay;

  currentDate.setDate(
    currentDate.getDate() +
      daysUntilNextMonday,
  );

  return toDateKey(currentDate);
}

function getCurrentWeekDateRange() {
  const currentDate = new Date();
  const currentDay = currentDate.getDay();
  const daysFromMonday =
    currentDay === 0 ? 6 : currentDay - 1;

  currentDate.setDate(
    currentDate.getDate() - daysFromMonday,
  );

  const dateFrom = toDateKey(currentDate);

  return {
    dateFrom,
    dateTo: addDaysToDateKey(dateFrom, 6),
  };
}

function isNextWeekMondayDateKey(
  value: string,
) {
  return (
    Boolean(value) &&
    value ===
      getNextWeekMondayDateKey()
  );
}

function formatLockedWeekDate(
  value?: string,
) {
  if (!value) {
    return "";
  }

  const [year, month, day] =
    value.split("-");

  if (
    !year ||
    !month ||
    !day
  ) {
    return value;
  }

  return `${day}-${month}-${year}`;
}

type LockedWeekDateInputProps = {
  value?: string;
};

function LockedWeekDateInput({
  value,
}: LockedWeekDateInputProps) {
  return (
    <Input
      value={formatLockedWeekDate(
        value,
      )}
      readOnly
      disabled
    />
  );
}

function addDaysToDateKey(
  dateKey: string,
  amount: number,
) {
  const date = new Date(`${dateKey}T00:00:00`);
  date.setDate(date.getDate() + amount);

  const year = date.getFullYear();
  const month = String(
    date.getMonth() + 1,
  ).padStart(2, "0");
  const day = String(date.getDate()).padStart(
    2,
    "0",
  );

  return `${year}-${month}-${day}`;
}


function isRecord(
  value: unknown,
): value is Record<string, unknown> {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}

function getWeeklyDraftStorageKey(
  facilityId: string,
) {
  return `${WEEKLY_DRAFT_STORAGE_PREFIX}:${facilityId}`;
}

function readWeeklyDraft(
  facilityId: string,
  expectedFromDate: string,
): BulkGenerateFormValues | null {
  if (
    typeof window === "undefined" ||
    !facilityId
  ) {
    return null;
  }

  const storageKey =
    getWeeklyDraftStorageKey(
      facilityId,
    );

  try {
    const rawValue =
      window.localStorage.getItem(
        storageKey,
      );

    if (!rawValue) {
      return null;
    }

    const parsed: unknown =
      JSON.parse(rawValue);

    if (
      !isRecord(parsed) ||
      parsed.version !== 1 ||
      !isRecord(parsed.values)
    ) {
      window.localStorage.removeItem(
        storageKey,
      );
      return null;
    }

    const values =
      parsed.values;

    if (
      values.facilityId !==
        facilityId ||
      values.fromDate !==
        expectedFromDate ||
      !Array.isArray(
        values.slotGroups,
      )
    ) {
      window.localStorage.removeItem(
        storageKey,
      );
      return null;
    }

    return values as unknown as
      BulkGenerateFormValues;
  } catch {
    window.localStorage.removeItem(
      storageKey,
    );
    return null;
  }
}

function saveWeeklyDraft(
  values: BulkGenerateFormValues,
) {
  if (
    typeof window === "undefined" ||
    !values.facilityId ||
    !values.fromDate
  ) {
    return;
  }

  const draft: BulkGenerateDraft = {
    version: 1,
    savedAt:
      new Date().toISOString(),
    values,
  };

  window.localStorage.setItem(
    getWeeklyDraftStorageKey(
      values.facilityId,
    ),
    JSON.stringify(draft),
  );
}

function clearWeeklyDraft(
  facilityId: string,
) {
  if (
    typeof window === "undefined" ||
    !facilityId
  ) {
    return;
  }

  window.localStorage.removeItem(
    getWeeklyDraftStorageKey(
      facilityId,
    ),
  );
}

function mergeDraftSlotGroups(
  slots: ShiftSlotLookupItem[],
  draft:
    | BulkGenerateFormValues
    | null,
): BulkSlotGroupFormValue[] {
  const draftBySlotId =
    new Map(
      (draft?.slotGroups ?? [])
        .filter(
          (group) =>
            Boolean(group?.slotId),
        )
        .map((group) => [
          group.slotId,
          group,
        ]),
    );

  return slots.map((slot) => ({
    slotId: slot.id,
    assignments:
      draftBySlotId.get(slot.id)
        ?.assignments ?? [],
  }));
}


function getResponseMessage(
  raw: unknown,
  fallback: string,
) {
  if (!isRecord(raw)) return fallback;

  if (typeof raw.message === "string") {
    return raw.message;
  }

  if (
    isRecord(raw.data) &&
    typeof raw.data.message === "string"
  ) {
    return raw.data.message;
  }

  return fallback;
}


type BulkGenerationIssue = {
  source: "conflict" | "skipped";
  slotAssignmentIndex: number;
  assignmentIndex: number;
  shiftDate: string;
  startTime: string;
  endTime: string;
  staffId: string;
  roomId: string;
  reason: string;
  hasDoctorConflict: boolean;
  hasRoomConflict: boolean;
};

type BulkGenerationResult = {
  recognized: boolean;
  canConfirm?: boolean;
  allOrNothingRejected: boolean;
  totalCandidates: number;
  valid: number;
  skipped: number;
  conflicted: number;
  createdCount: number;
  issues: BulkGenerationIssue[];
};

function readNumberValue(
  value: unknown,
  fallback = 0,
) {
  const parsed = Number(value);

  return Number.isFinite(parsed)
    ? parsed
    : fallback;
}

function readStringValue(value: unknown) {
  return typeof value === "string"
    ? value.trim()
    : "";
}

function readRecordArray(value: unknown) {
  return Array.isArray(value)
    ? value.filter(isRecord)
    : [];
}

function readBulkGenerationResult(
  raw: unknown,
): BulkGenerationResult {
  const rawRecord = isRecord(raw)
    ? raw
    : {};

  const root =
    isRecord(rawRecord.data) &&
    (
      "summary" in rawRecord.data ||
      "conflictItems" in rawRecord.data ||
      "skippedItems" in rawRecord.data ||
      "createdCount" in rawRecord.data
    )
      ? rawRecord.data
      : rawRecord;

  const summary = isRecord(root.summary)
    ? root.summary
    : {};

  const conflictItems =
    readRecordArray(root.conflictItems);
  const skippedItems =
    readRecordArray(root.skippedItems);

  function parseIssue(
    issue: Record<string, unknown>,
    source: BulkGenerationIssue["source"],
  ): BulkGenerationIssue {
    const candidate = isRecord(
      issue.candidate,
    )
      ? issue.candidate
      : {};

    const doctorConflicts =
      readRecordArray(
        issue.doctorConflicts,
      );
    const roomConflicts =
      readRecordArray(
        issue.roomConflicts,
      );

    return {
      source,
      slotAssignmentIndex:
        readNumberValue(
          issue.slotAssignmentIndex ??
            candidate.slotAssignmentIndex,
          -1,
        ),
      assignmentIndex:
        readNumberValue(
          issue.assignmentIndex ??
            candidate.assignmentIndex,
          -1,
        ),
      shiftDate:
        readStringValue(
          issue.shiftDate ??
            candidate.shiftDate,
        ),
      startTime:
        readStringValue(
          candidate.startTime ??
            issue.startTime,
        ),
      endTime:
        readStringValue(
          candidate.endTime ??
            issue.endTime,
        ),
      staffId:
        readStringValue(
          candidate.staffId ??
            issue.staffId,
        ),
      roomId:
        readStringValue(
          candidate.roomId ??
            issue.roomId,
        ),
      reason:
        readStringValue(
          issue.reason ??
            issue.message,
        ) ||
        (
          source === "conflict"
            ? "Ca trực bị trùng lịch."
            : "Ca trực không thể được tạo."
        ),
      hasDoctorConflict:
        doctorConflicts.length > 0 ||
        Boolean(
          issue.doctorConflict ??
            issue.hasDoctorConflict,
        ),
      hasRoomConflict:
        roomConflicts.length > 0 ||
        Boolean(
          issue.roomConflict ??
            issue.hasRoomConflict,
        ),
    };
  }

  const recognized =
    "summary" in root ||
    "canConfirm" in root ||
    "allOrNothingRejected" in root ||
    "createdCount" in root ||
    "conflictItems" in root ||
    "skippedItems" in root;

  return {
    recognized,
    canConfirm:
      typeof root.canConfirm ===
      "boolean"
        ? root.canConfirm
        : undefined,
    allOrNothingRejected:
      root.allOrNothingRejected ===
      true,
    totalCandidates:
      readNumberValue(
        summary.totalCandidates,
      ),
    valid:
      readNumberValue(summary.valid),
    skipped:
      readNumberValue(
        summary.skipped,
        skippedItems.length,
      ),
    conflicted:
      readNumberValue(
        summary.conflicted,
        conflictItems.length,
      ),
    createdCount:
      readNumberValue(
        root.createdCount,
        Array.isArray(
          root.createdShifts,
        )
          ? root.createdShifts.length
          : 0,
      ),
    issues: [
      ...conflictItems.map(
        (issue) =>
          parseIssue(
            issue,
            "conflict",
          ),
      ),
      ...skippedItems.map(
        (issue) =>
          parseIssue(
            issue,
            "skipped",
          ),
      ),
    ],
  };
}

function formatIssueDate(value: string) {
  const [
    year,
    month,
    day,
  ] = value.split("-");

  if (!year || !month || !day) {
    return value || "Không rõ ngày";
  }

  return `${day}/${month}/${year}`;
}

function formatIssueTime(value: string) {
  return value
    ? value.slice(0, 5)
    : "";
}

export function DoctorShiftBulkGenerateModal({
  open,
  facilities,
  rooms,
  doctors,
  onClose,
  onGenerated,
}: DoctorShiftBulkGenerateModalProps) {
  const { message: messageApi } = App.useApp();
  const [form] =
    Form.useForm<BulkGenerateFormValues>();
  const [shiftSlots, setShiftSlots] = useState<
    ShiftSlotLookupItem[]
  >([]);
  const [slotsLoading, setSlotsLoading] =
    useState(false);
  const [previewLoading, setPreviewLoading] =
    useState(false);
  const [importWeekLoading, setImportWeekLoading] =
    useState(false);
  const [confirmLoading, setConfirmLoading] =
    useState(false);
  const [previewModalOpen, setPreviewModalOpen] =
    useState(false);
  const [previewPayload, setPreviewPayload] =
    useState<BulkGenerateDoctorShiftsInput | null>(
      null,
    );
  const [previewValues, setPreviewValues] =
    useState<BulkGenerateFormValues | null>(
      null,
    );
  const [previewResult, setPreviewResult] =
    useState<BulkGenerationResult | null>(
      null,
    );
  const [error, setError] = useState<
    string | null
  >(null);
  const [
    generationIssues,
    setGenerationIssues,
  ] = useState<string[]>([]);
  const issueFieldPathsRef = useRef<
    BulkGenerationIssueFieldPath[]
  >([]);
  const pendingDraftRef = useRef<
    BulkGenerateFormValues | null
  >(null);

  const watchedFacilityId =
    Form.useWatch("facilityId", form) ?? "";
  const watchedFromDate =
    Form.useWatch("fromDate", form) ?? "";
  const watchedSlotGroups =
    Form.useWatch("slotGroups", form) ?? [];

  const slotById = useMemo(
    () =>
      new Map(
        shiftSlots.map((slot) => [slot.id, slot]),
      ),
    [shiftSlots],
  );

  const previewCanConfirm =
    Boolean(
      previewResult &&
      previewResult.recognized &&
      previewResult.valid > 0,
    );

  const roomOptions = useMemo(
    () =>
      rooms
        .filter(
          (room) =>
            room.facilityId === watchedFacilityId,
        )
        .map((room) => ({
          value: room.id,
          label: `${room.name}${
            room.floor
              ? ` · ${room.floor}`
              : ""
          }`,
        })),
    [rooms, watchedFacilityId],
  );

  const doctorOptions = useMemo(
    () =>
      doctors
        .filter(
          (doctor) =>
            doctor.status === "active" &&
            doctor.staffId &&
            doctor.roleId &&
            doctor.facilityIds.includes(
              watchedFacilityId,
            ),
        )
        .map((doctor) => ({
          value: doctor.staffId,
          label: `${doctor.title} ${doctor.name} · ${doctor.specialty}`,
        })),
    [doctors, watchedFacilityId],
  );

  useEffect(() => {
    if (!open) return;

    const nextWeekMonday =
      getNextWeekMondayDateKey();
    const defaultFacilityId =
      facilities.length === 1
        ? facilities[0]?.id
        : undefined;
    const restoredDraft =
      defaultFacilityId
        ? readWeeklyDraft(
            defaultFacilityId,
            nextWeekMonday,
          )
        : null;

    const timer = window.setTimeout(() => {
      pendingDraftRef.current =
        restoredDraft;

      form.resetFields();
      form.setFieldsValue({
        facilityId:
          defaultFacilityId,
        fromDate:
          nextWeekMonday,
        slotGroups: [],
      });
      setShiftSlots([]);
      setError(null);
      setGenerationIssues([]);
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);
      issueFieldPathsRef.current = [];
    }, 0);

    return () => {
      window.clearTimeout(timer);
    };
  }, [
    facilities,
    form,
    open,
  ]);

  useEffect(() => {
    if (!open || !watchedFacilityId) {
      return;
    }

    let cancelled = false;

    void Promise.resolve()
      .then(() => {
        if (!cancelled) {
          setSlotsLoading(true);
        }

        return getShiftSlotLookup({
          facilityId: watchedFacilityId,
          status: "active",
          limit: 40,
        });
      })
      .then((slots) => {
        if (cancelled) return;

        setShiftSlots(slots);

        const restoredDraft =
          pendingDraftRef.current;
        const slotGroups =
          mergeDraftSlotGroups(
            slots,
            restoredDraft,
          );

        form.setFieldsValue({
          slotGroups,
        });

        pendingDraftRef.current =
          null;
      })
      .catch((loadError) => {
        if (cancelled) return;

        setShiftSlots([]);
        pendingDraftRef.current =
          null;
        form.setFieldsValue({
          slotGroups: [],
        });
        setError(getErrorMessage(loadError));
      })
      .finally(() => {
        if (!cancelled) {
          setSlotsLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [
    form,
    open,
    watchedFacilityId,
  ]);

  function clearGenerationIssueErrors() {
    const paths =
      issueFieldPathsRef.current;

    if (paths.length > 0) {
      form.setFields(
        paths.map((name) => ({
          name,
          errors: [] as string[],
        })),
      );
    }

    issueFieldPathsRef.current = [];
  }

  function getIssueDisplayData(
    issue: BulkGenerationIssue,
    values: BulkGenerateFormValues,
  ) {
    const group =
      values.slotGroups?.[
        issue.slotAssignmentIndex
      ];
    const assignment =
      group?.assignments?.[
        issue.assignmentIndex
      ];

    const slotId =
      group?.slotId ?? "";
    const slot =
      slotById.get(slotId);

    const staffId =
      issue.staffId ||
      assignment?.staffId ||
      "";
    const doctor = doctors.find(
      (item) =>
        item.staffId === staffId,
    );

    const roomId =
      issue.roomId ||
      assignment?.roomId ||
      "";
    const room = rooms.find(
      (item) => item.id === roomId,
    );

    const slotLabel =
      slot?.name ||
      slot?.code ||
      (
        issue.slotAssignmentIndex >= 0
          ? `Khung ca ${
              issue.slotAssignmentIndex +
              1
            }`
          : "Không rõ khung ca"
      );

    const assignmentLabel =
      issue.assignmentIndex >= 0
        ? `Phân công ${
            issue.assignmentIndex + 1
          }`
        : "Không rõ phân công";

    const doctorLabel = doctor
      ? `${doctor.title} ${doctor.name}`
      : staffId
        ? `Nhân sự #${staffId}`
        : "Bác sĩ đã chọn";

    const roomLabel =
      room?.name ||
      (
        roomId
          ? `Phòng #${roomId}`
          : "Phòng đã chọn"
      );

    const timeRange =
      issue.startTime &&
      issue.endTime
        ? `${formatIssueTime(
            issue.startTime,
          )} - ${formatIssueTime(
            issue.endTime,
          )}`
        : "";

    return {
      slotLabel,
      assignmentLabel,
      doctorLabel,
      roomLabel,
      timeRange,
    };
  }

  function applyGenerationIssues(
    result: BulkGenerationResult,
    values: BulkGenerateFormValues,
  ) {
    const fieldErrorMap = new Map<
      string,
      {
        name: BulkGenerationIssueFieldPath;
        errors: string[];
      }
    >();

    const issueMessages =
      result.issues.map(
        (issue) => {
          const display =
            getIssueDisplayData(
              issue,
              values,
            );
          const dateLabel =
            formatIssueDate(
              issue.shiftDate,
            );
          const prefix = [
            dateLabel,
            display.timeRange,
            display.slotLabel,
            display.assignmentLabel,
          ]
            .filter(Boolean)
            .join(" · ");

          const details: string[] = [];

          if (
            issue.hasDoctorConflict
          ) {
            details.push(
              `${display.doctorLabel} đã có lịch trùng thời gian`,
            );
          }

          if (
            issue.hasRoomConflict
          ) {
            details.push(
              `${display.roomLabel} đã được sử dụng trong thời gian này`,
            );
          }

          if (
            details.length === 0
          ) {
            details.push(issue.reason);
          } else if (
            issue.reason &&
            !details.includes(
              issue.reason,
            )
          ) {
            details.push(issue.reason);
          }

          const fieldMessage =
            `${dateLabel}${
              display.timeRange
                ? ` (${display.timeRange})`
                : ""
            }: ${details.join(". ")}.`;

          function addFieldError(
            field:
              | "staffId"
              | "roomId",
          ) {
            if (
              issue.slotAssignmentIndex <
                0 ||
              issue.assignmentIndex < 0
            ) {
              return;
            }

            const name:
              BulkGenerationIssueFieldPath =
              field === "staffId"
                ? [
                    "slotGroups",
                    issue.slotAssignmentIndex,
                    "assignments",
                    issue.assignmentIndex,
                    "staffId",
                  ]
                : [
                    "slotGroups",
                    issue.slotAssignmentIndex,
                    "assignments",
                    issue.assignmentIndex,
                    "roomId",
                  ];
            const key = name.join(".");
            const current =
              fieldErrorMap.get(key);

            if (current) {
              current.errors.push(
                fieldMessage,
              );
            } else {
              fieldErrorMap.set(key, {
                name,
                errors: [fieldMessage],
              });
            }
          }

          if (
            issue.hasDoctorConflict
          ) {
            addFieldError("staffId");
          }

          if (
            issue.hasRoomConflict
          ) {
            addFieldError("roomId");
          }

          return `${prefix}: ${details.join(
            ". ",
          )}.`;
        },
      );

    if (
      issueMessages.length === 0
    ) {
      issueMessages.push(
        `Backend từ chối tạo lịch: ${result.skipped} lịch bị bỏ qua, ${result.conflicted} lịch bị trùng và ${result.createdCount} lịch được tạo.`,
      );
    }

    const fieldErrors =
      Array.from(
        fieldErrorMap.values(),
      );

    if (fieldErrors.length > 0) {
      form.setFields(fieldErrors);
      issueFieldPathsRef.current =
        fieldErrors.map(
          (item) => item.name,
        );

      window.setTimeout(() => {
        form.scrollToField(
          fieldErrors[0].name,
        );
      }, 0);
    }

    setGenerationIssues(
      issueMessages,
    );

    return issueMessages;
  }

  function buildPayload(
    values: BulkGenerateFormValues,
  ): BulkGenerateDoctorShiftsInput {
    if (
      !isNextWeekMondayDateKey(
        values.fromDate,
      )
    ) {
      throw new Error(
        "Chỉ được xếp lịch cho tuần kế tiếp.",
      );
    }

    const toDate =
      addDaysToDateKey(
        values.fromDate,
        6,
      );

    const slotAssignments =
      (values.slotGroups ?? [])
        .map((group) => {
          const assignments =
            (group.assignments ?? []).map(
              (assignment) => {
                const doctor = doctors.find(
                  (item) =>
                    item.staffId ===
                    assignment.staffId,
                );

                if (!doctor) {
                  throw new Error(
                    "Không tìm thấy thông tin nhân sự của bác sĩ đã chọn.",
                  );
                }

                return {
                  staffId:
                    assignment.staffId.trim(),
                  roleId: String(
                    doctor.roleId,
                  ),
                  roomId:
                    assignment.roomId.trim(),
                  workingDays:
                    assignment.workingDays,
                  maxAppointments: Number(
                    assignment.maxAppointments,
                  ),
                  status: assignment.status,
                };
              },
            );

          return {
            slotId: group.slotId.trim(),
            assignments,
          };
        })
        .filter(
          (group) =>
            group.assignments.length > 0,
        );

    if (slotAssignments.length === 0) {
      throw new Error(
        "Vui lòng phân công ít nhất một bác sĩ vào một khung ca.",
      );
    }

    return {
      facilityId: values.facilityId.trim(),
      fromDate: values.fromDate,
      toDate,
      slotAssignments,
      saveOnlyValid: true,
    };
  }

  async function handleImportCurrentWeek() {
    setError(null);
    setGenerationIssues([]);
    clearGenerationIssueErrors();

    if (!watchedFacilityId) {
      const message =
        "Vui lòng chọn cơ sở trước khi lấy lịch tuần này.";
      setError(message);
      messageApi.warning(message);
      return;
    }

    const { dateFrom, dateTo } =
      getCurrentWeekDateRange();

    setImportWeekLoading(true);

    try {
      const schedule =
        await getGroupedDoctorShifts({
          facilityId: watchedFacilityId,
          dateFrom,
          dateTo,
        });
      const activeSlotIds = new Set(
        shiftSlots.map((slot) => slot.id),
      );
      const availableRoomIds = new Set(
        rooms
          .filter(
            (room) =>
              room.facilityId === watchedFacilityId,
          )
          .map((room) => room.id),
      );
      const assignmentMaps = new Map<
        string,
        Map<string, BulkAssignmentFormValue>
      >();
      let skippedGroups = 0;

      for (const group of schedule.groups ?? []) {
        const sourceShift = group.shifts?.[0];

        if (
          !sourceShift ||
          sourceShift.status === "cancelled"
        ) {
          skippedGroups += 1;
          continue;
        }

        const slotId = String(sourceShift.slotId ?? "");
        const staffId = String(sourceShift.staffId ?? "");
        const roleId = String(sourceShift.roleId ?? "");
        const roomId = String(sourceShift.roomId ?? "");
        const doctor = doctors.find(
          (item) =>
            item.staffId === staffId &&
            String(item.roleId) === roleId &&
            item.status === "active" &&
            item.facilityIds.includes(
              watchedFacilityId,
            ),
        );
        const workingDays = (
          group.workingDays ?? []
        ).filter((day) =>
          WORKING_DAY_OPTIONS.some(
            (option) => option.value === day,
          ),
        );

        if (
          !slotId ||
          !activeSlotIds.has(slotId) ||
          !doctor ||
          !roomId ||
          !availableRoomIds.has(roomId) ||
          workingDays.length === 0
        ) {
          skippedGroups += 1;
          continue;
        }

        const status =
          sourceShift.status === "off"
            ? "off"
            : "available";
        const maxAppointments = Math.max(
          1,
          Number(sourceShift.maxAppointments) || 8,
        );
        const assignmentKey = [
          staffId,
          roomId,
          status,
          maxAppointments,
        ].join(":");
        const assignments =
          assignmentMaps.get(slotId) ?? new Map();
        const existing = assignments.get(assignmentKey);

        assignments.set(assignmentKey, {
          staffId,
          roomId,
          status,
          maxAppointments,
          workingDays: Array.from(
            new Set([
              ...(existing?.workingDays ?? []),
              ...workingDays,
            ]),
          ),
        });
        assignmentMaps.set(slotId, assignments);
      }

      const slotGroups = shiftSlots.map((slot) => ({
        slotId: slot.id,
        assignments: Array.from(
          assignmentMaps.get(slot.id)?.values() ?? [],
        ),
      }));
      const importedAssignments = slotGroups.reduce(
        (total, group) =>
          total + group.assignments.length,
        0,
      );

      if (importedAssignments === 0) {
        const message =
          `Không có lịch phù hợp để lấy từ tuần ${formatIssueDate(dateFrom)} - ${formatIssueDate(dateTo)}.`;
        setError(message);
        messageApi.warning(message);
        return;
      }

      const nextValues: BulkGenerateFormValues = {
        facilityId: watchedFacilityId,
        fromDate:
          watchedFromDate ||
          getNextWeekMondayDateKey(),
        slotGroups,
      };

      form.setFieldsValue(nextValues);
      saveWeeklyDraft(nextValues);
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);

      const skippedMessage =
        skippedGroups > 0
          ? ` Bỏ qua ${skippedGroups} nhóm đã hủy hoặc không còn hợp lệ.`
          : "";
      messageApi.success(
        `Đã lấy ${importedAssignments} phân công từ tuần ${formatIssueDate(dateFrom)} - ${formatIssueDate(dateTo)}.${skippedMessage}`,
      );
    } catch (importError) {
      const message = getErrorMessage(importError);
      setError(message);
      messageApi.error(message);
    } finally {
      setImportWeekLoading(false);
    }
  }

  async function handlePreview() {
    setError(null);
    setGenerationIssues([]);
    clearGenerationIssueErrors();

    try {
      const values =
        await form.validateFields();
      const payload = buildPayload(values);

      setPreviewLoading(true);

      const response =
        await previewBulkGeneratedShifts(
          payload,
        );
      const result =
        readBulkGenerationResult(
          response,
        );

      if (!result.recognized) {
        throw new Error(
          "Không đọc được kết quả xem trước từ hệ thống.",
        );
      }

      const hasIssues =
        result.skipped > 0 ||
        result.conflicted > 0 ||
        result.canConfirm === false ||
        result.allOrNothingRejected;

      if (hasIssues) {
        applyGenerationIssues(
          result,
          values,
        );
      } else {
        setGenerationIssues([]);
      }

      setPreviewPayload(payload);
      setPreviewValues(values);
      setPreviewResult(result);
      setPreviewModalOpen(true);
    } catch (previewError) {
      const message =
        getErrorMessage(previewError);

      setError(message);

      if (
        !(
          isRecord(previewError) &&
          "errorFields" in previewError
        )
      ) {
        messageApi.error(message);
      }
    } finally {
      setPreviewLoading(false);
    }
  }

  async function handleConfirmPreview() {
    if (
      !previewPayload ||
      !previewValues ||
      !previewResult ||
      !previewCanConfirm
    ) {
      return;
    }

    setConfirmLoading(true);
    setError(null);

    try {
      const response =
        await confirmAutoGeneratedShifts(
          previewPayload,
        );
      const result =
        readBulkGenerationResult(
          response,
        );

      const createdCount =
        result.createdCount;

      if (
        result.recognized &&
        createdCount === 0
      ) {
        const issues =
          applyGenerationIssues(
            result,
            previewValues,
          );

        setPreviewResult(result);

        const summaryMessage =
          "Không có ca trực hợp lệ nào được tạo.";

        setError(summaryMessage);
        setGenerationIssues(issues);
        messageApi.error(
          summaryMessage,
        );
        return;
      }

      await onGenerated({
        fromDate:
          previewPayload.fromDate,
        toDate: previewPayload.toDate,
      });

      messageApi.success(
        getResponseMessage(
          response,
          result.recognized &&
          result.createdCount > 0
            ? (
                result.skipped > 0 ||
                result.conflicted > 0
                  ? `Đã tạo ${result.createdCount} ca trực hợp lệ. Các ca bị trùng hoặc bị bỏ qua không được tạo.`
                  : `Tạo thành công ${result.createdCount} ca trực.`
              )
            : "Tạo lịch trực 1 tuần thành công.",
        ),
      );

      clearWeeklyDraft(
        previewPayload.facilityId,
      );
      pendingDraftRef.current =
        null;
      setPreviewModalOpen(false);
      setPreviewPayload(null);
      setPreviewValues(null);
      setPreviewResult(null);
      setGenerationIssues([]);
      form.resetFields();
      onClose();
    } catch (confirmError) {
      const message =
        getErrorMessage(confirmError);

      setError(message);
      messageApi.error(message);
    } finally {
      setConfirmLoading(false);
    }
  }

  function handleCancel() {
    if (
      previewLoading ||
      confirmLoading
    ) {
      return;
    }

    const currentValues =
      form.getFieldsValue(
        true,
      );

    saveWeeklyDraft(
      currentValues,
    );

    clearGenerationIssueErrors();
    setError(null);
    setGenerationIssues([]);
    setPreviewModalOpen(false);
    setPreviewPayload(null);
    setPreviewValues(null);
    setPreviewResult(null);
    onClose();
  }

  return (
    <>
      <Modal
      open={open}
      centered
      width={1120}
      title={null}
      footer={null}
      closable={false}
      onCancel={handleCancel}
      mask={{
        closable:
          !previewLoading &&
          !confirmLoading,
      }}
      destroyOnHidden
      styles={{
        body: {
          maxHeight: "82vh",
          overflow: "hidden",
        },
      }}
    >
      <div className="relative mb-5 border-b border-slate-200 pb-4 pr-12">
        <button
          type="button"
          aria-label="Đóng"
          disabled={
            previewLoading ||
            confirmLoading
          }
          onClick={handleCancel}
          className="absolute right-0 top-0 z-10 flex h-9 w-9 items-center justify-center rounded-full text-slate-400 transition hover:bg-slate-100 hover:text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-start gap-3">
          <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-white">
            <Calendar className="h-5 w-5" />
          </span>

          <div>
            <Title
              level={4}
              className="!mb-1 !text-slate-950"
            >
              Tạo lịch trực 1 tuần
            </Title>

            <Text type="secondary">
              Phân công bác sĩ theo từng khung ca, phòng và ngày làm việc. Hệ thống chỉ tạo lịch cho tuần kế tiếp, từ Thứ 2 đến Chủ nhật.
            </Text>

            <Text
              type="secondary"
              className="mt-1 block text-xs"
            >
              Bản nháp được tự động lưu và sẽ được khôi phục khi mở lại.
            </Text>
          </div>
        </div>
      </div>

      <div
        className="pr-3"
        style={{
          maxHeight: "calc(82vh - 180px)",
          overflowY: "auto",
          scrollbarGutter: "stable",
        }}
      >
        {error ? (
          <Alert
            type="error"
            title={error}
            showIcon
            closable
            className="mb-4"
            onClose={() =>
              setError(null)
            }
          />
        ) : null}

      <Form<BulkGenerateFormValues>
        form={form}
        layout="vertical"
        requiredMark="optional"
        onValuesChange={(
          changedValues,
          allValues,
        ) => {
          if (
            generationIssues.length >
              0 ||
            issueFieldPathsRef.current
              .length > 0
          ) {
            clearGenerationIssueErrors();
            setGenerationIssues([]);
            setError(null);
          }

          setPreviewModalOpen(false);
          setPreviewPayload(null);
          setPreviewValues(null);
          setPreviewResult(null);

          if (
            "facilityId" in
            changedValues
          ) {
            const facilityId =
              changedValues.facilityId as string;

            setShiftSlots([]);
            setSlotsLoading(
              Boolean(facilityId),
            );
            form.setFieldsValue({
              slotGroups: [],
            });
          }

          saveWeeklyDraft(
            allValues,
          );
        }}
      >
        <Row gutter={[16, 0]}>
          <Col xs={24} lg={12}>
            <Form.Item
              name="facilityId"
              label="Cơ sở"
              rules={[
                {
                  required: true,
                  message:
                    "Vui lòng chọn cơ sở.",
                },
              ]}
            >
              <Select
                showSearch
                optionFilterProp="label"
                disabled={
                  facilities.length === 1
                }
                placeholder="Chọn cơ sở khám"
                options={facilities.map(
                  (facility) => ({
                    value: facility.id,
                    label: `${facility.name} (${facility.code})`,
                  }),
                )}
              />
            </Form.Item>
          </Col>

          <Col xs={24} lg={12}>
            <Form.Item
              name="fromDate"
              label="Tuần được xếp lịch"
              extra={
                watchedFromDate
                  ? `Từ Thứ 2 ${formatIssueDate(
                      watchedFromDate,
                    )} đến Chủ nhật ${formatIssueDate(
                      addDaysToDateKey(
                        watchedFromDate,
                        6,
                      ),
                    )}.`
                  : "Hệ thống tự xác định tuần kế tiếp."
              }
              rules={[
                {
                  required: true,
                  message:
                    "Không xác định được tuần kế tiếp.",
                },
                {
                  validator: async (
                    _rule,
                    value?: string,
                  ) => {
                    if (
                      value &&
                      !isNextWeekMondayDateKey(
                        value,
                      )
                    ) {
                      throw new Error(
                        "Chỉ được xếp lịch cho tuần kế tiếp.",
                      );
                    }
                  },
                },
              ]}
            >
              <LockedWeekDateInput />
            </Form.Item>
          </Col>
        </Row>

        <div className="mb-3 flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
          <div>
            <Text
              strong
              className="block text-slate-950"
            >
              Phân công theo khung ca
            </Text>

            <Text
              type="secondary"
              className="text-sm"
            >
              Mỗi bác sĩ chọn phòng, các ngày làm việc trong tuần và số lịch tối đa.
            </Text>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Button
              icon={<Copy className="h-4 w-4" />}
              loading={importWeekLoading}
              disabled={
                !watchedFacilityId ||
                slotsLoading ||
                previewLoading ||
                confirmLoading
              }
              onClick={() =>
                void handleImportCurrentWeek()
              }
            >
              Lấy lịch tuần này
            </Button>

            {watchedFacilityId &&
            !slotsLoading ? (
              <Tag color="blue">
                {shiftSlots.length} khung ca
              </Tag>
            ) : null}
          </div>
        </div>

        {!watchedFacilityId ? (
          <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center">
            <Clock className="mx-auto h-7 w-7 text-slate-400" />

            <Text className="mt-3 block font-medium text-slate-700">
              Vui lòng chọn cơ sở
            </Text>

            <Text
              type="secondary"
              className="mt-1 block text-sm"
            >
              Các khung ca hoạt động của cơ sở sẽ hiển thị tại đây.
            </Text>
          </div>
        ) : slotsLoading ? (
          <div className="rounded-xl border border-slate-200 bg-slate-50 px-5 py-10 text-center">
            <Text type="secondary">
              Đang tải danh sách khung ca...
            </Text>
          </div>
        ) : shiftSlots.length === 0 ? (
          <Alert
            type="warning"
            showIcon
            title="Cơ sở chưa có khung ca hoạt động"
          />
        ) : (
          <Form.List name="slotGroups">
            {(groupFields) => (
              <div className="grid gap-4">
                {groupFields.map(
                  (
                    groupField,
                    groupIndex,
                  ) => {
                    const group =
                      watchedSlotGroups[
                        groupIndex
                      ];
                    const slot =
                      slotById.get(
                        group?.slotId ??
                          shiftSlots[
                            groupIndex
                          ]?.id ??
                          "",
                      );

                    if (!slot) {
                      return null;
                    }

                    const assignmentCount =
                      group?.assignments
                        ?.length ?? 0;

                    return (
                      <div
                        key={
                          groupField.key
                        }
                        className="overflow-hidden rounded-xl border border-slate-200 bg-white"
                      >
                        <Form.Item
                          name={[
                            groupField.name,
                            "slotId",
                          ]}
                          hidden
                        >
                          <Input />
                        </Form.Item>

                        <div className="flex flex-col justify-between gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3 sm:flex-row sm:items-center">
                          <div className="flex items-center gap-3">
                            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-slate-900 text-white">
                              <Clock className="h-5 w-5" />
                            </span>

                            <div>
                              <Text
                                strong
                                className="block text-slate-950"
                              >
                                {slot.name}
                              </Text>

                              <Text
                                type="secondary"
                                className="text-sm"
                              >
                                {slot.code} ·{" "}
                                {slot.startTime} -{" "}
                                {slot.endTime}
                              </Text>
                            </div>
                          </div>

                          <Tag
                            color={
                              assignmentCount >
                              0
                                ? "green"
                                : "default"
                            }
                          >
                            {assignmentCount >
                            0
                              ? `${assignmentCount} phân công`
                              : "Chưa phân công"}
                          </Tag>
                        </div>

                        <div className="p-4">
                          <Form.List
                            name={[
                              groupField.name,
                              "assignments",
                            ]}
                          >
                            {(
                              assignmentFields,
                              {
                                add,
                                remove,
                              },
                            ) => (
                              <div className="flex flex-col gap-3">
                                {assignmentFields.length ===
                                0 ? (
                                  <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-5 text-center">
                                    <Text
                                      type="secondary"
                                      className="text-sm"
                                    >
                                      Chưa có bác sĩ trong khung ca này.
                                    </Text>
                                  </div>
                                ) : null}

                                {assignmentFields.map(
                                  (
                                    assignmentField,
                                    assignmentIndex,
                                  ) => (
                                    <div
                                      key={
                                        assignmentField.key
                                      }
                                      className="rounded-lg border border-slate-200 bg-slate-50/70 p-3"
                                    >
                                      <div className="mb-2 flex items-center justify-between">
                                        <Text
                                          strong
                                          className="text-sm text-slate-700"
                                        >
                                          Phân công{" "}
                                          {assignmentIndex +
                                            1}
                                        </Text>

                                        <Button
                                          danger
                                          type="text"
                                          size="small"
                                          icon={
                                            <Trash2 className="h-4 w-4" />
                                          }
                                          onClick={() =>
                                            remove(
                                              assignmentField.name,
                                            )
                                          }
                                        >
                                          Xóa
                                        </Button>
                                      </div>

                                      <Row
                                        gutter={[
                                          12,
                                          0,
                                        ]}
                                      >
                                        <Col
                                          xs={24}
                                          lg={9}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "staffId",
                                            ]}
                                            label="Bác sĩ"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn bác sĩ.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              showSearch
                                              optionFilterProp="label"
                                              placeholder="Chọn bác sĩ"
                                              options={
                                                doctorOptions
                                              }
                                              notFoundContent="Cơ sở chưa có bác sĩ phù hợp"
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={12}
                                          lg={6}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "roomId",
                                            ]}
                                            label="Phòng"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn phòng.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              showSearch
                                              optionFilterProp="label"
                                              placeholder="Chọn phòng"
                                              options={
                                                roomOptions
                                              }
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={6}
                                          lg={4}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "maxAppointments",
                                            ]}
                                            label="Số lịch tối đa"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Nhập số lịch.",
                                              },
                                            ]}
                                          >
                                            <InputNumber
                                              min={1}
                                              className="w-full"
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={6}
                                          lg={5}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "status",
                                            ]}
                                            label="Trạng thái"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn trạng thái.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              options={[
                                                {
                                                  value:
                                                    "available",
                                                  label:
                                                    "Còn trống",
                                                },
                                                {
                                                  value:
                                                    "off",
                                                  label:
                                                    "Nghỉ",
                                                },
                                              ]}
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col xs={24}>
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "workingDays",
                                            ]}
                                            label="Ngày làm việc trong tuần"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn ít nhất một ngày làm việc.",
                                              },
                                            ]}
                                          >
                                            <Checkbox.Group
                                              options={getSlotWorkingDayOptions(
                                                slot,
                                              )}
                                              className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"
                                            />
                                          </Form.Item>
                                        </Col>
                                      </Row>
                                    </div>
                                  ),
                                )}

                                <Button
                                  type="dashed"
                                  block
                                  icon={
                                    <Plus className="h-4 w-4" />
                                  }
                                  onClick={() =>
                                    add({
                                      staffId:
                                        "",
                                      roomId: "",
                                      workingDays: getDefaultWorkingDays(
                                        slot,
                                      ),
                                      maxAppointments:
                                        8,
                                      status:
                                        "available",
                                    })
                                  }
                                >
                                  Thêm bác sĩ vào{" "}
                                  {slot.name}
                                </Button>
                              </div>
                            )}
                          </Form.List>
                        </div>
                      </div>
                    );
                  },
                )}
              </div>
            )}
          </Form.List>
        )}

      </Form>
      </div>

      <div className="mt-4 flex flex-col-reverse justify-end gap-2 border-t border-slate-200 pt-4 sm:flex-row">
        <Button
          disabled={
            previewLoading ||
            confirmLoading ||
            importWeekLoading
          }
          onClick={handleCancel}
        >
          Hủy
        </Button>

        <Button
          type="primary"
          loading={previewLoading}
          disabled={
            confirmLoading ||
            importWeekLoading
          }
          icon={
            <Eye className="h-4 w-4" />
          }
          onClick={() =>
            void handlePreview()
          }
        >
          Xem trước lịch tuần
        </Button>
      </div>
      </Modal>

      <DoctorShiftBulkPreviewModal
        open={previewModalOpen}
        totalCandidates={
          previewResult?.totalCandidates ??
          0
        }
        valid={previewResult?.valid ?? 0}
        skipped={
          previewResult?.skipped ?? 0
        }
        conflicted={
          previewResult?.conflicted ?? 0
        }
        issues={generationIssues}
        canConfirm={previewCanConfirm}
        confirmLoading={confirmLoading}
        onClose={() => {
          if (!confirmLoading) {
            setPreviewModalOpen(false);
          }
        }}
        onConfirm={
          handleConfirmPreview
        }
      />
    </>
  );
}
