"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  App,
  Button,
  Checkbox,
  Col,
  Form,
  Input,
  InputNumber,
  Modal,
  Row,
  Select,
  Switch,
  Tag,
  Typography,
} from "antd";
import {
  Calendar,
  Clock,
  Plus,
  Trash2,
  X,
} from "lucide-react";
import {
  confirmAutoGeneratedShifts,
} from "@/management/features/doctor-shifts/doctor-shifts.api";
import type {
  BulkGenerateDoctorShiftsInput,
  DoctorShiftStatus,
  DoctorShiftWorkingDay,
} from "@/management/features/doctor-shifts/doctor-shifts.types";
import { getShiftSlotLookup } from "@/management/features/shift-slots/shift-slots.api";
import type { ShiftSlotLookupItem } from "@/management/features/shift-slots/shift-slots.types";
import {
  getErrorMessage,
} from "./doctor-shift-modal.shared";
import type {
  DoctorOption,
  FacilityOption,
  RoomOption,
} from "./doctor-shift-modal.shared";

const { Text, Title } = Typography;

const WORKING_DAY_OPTIONS: Array<{
  label: string;
  value: DoctorShiftWorkingDay;
}> = [
  { label: "Thứ 2", value: "MON" },
  { label: "Thứ 3", value: "TUE" },
  { label: "Thứ 4", value: "WED" },
  { label: "Thứ 5", value: "THU" },
  { label: "Thứ 6", value: "FRI" },
  { label: "Thứ 7", value: "SAT" },
  { label: "Chủ nhật", value: "SUN" },
];

type BulkAssignmentFormValue = {
  staffId: string;
  roomId: string;
  workingDays: DoctorShiftWorkingDay[];
  maxAppointments: number;
  status: Extract<
    DoctorShiftStatus,
    "available" | "off"
  >;
};

type BulkSlotGroupFormValue = {
  slotId: string;
  assignments: BulkAssignmentFormValue[];
};

type BulkGenerateFormValues = {
  facilityId: string;
  fromDate: string;
  toDate: string;
  saveOnlyValid: boolean;
  slotGroups: BulkSlotGroupFormValue[];
};


type DoctorShiftBulkGenerateModalProps = {
  open: boolean;
  facilities: FacilityOption[];
  rooms: RoomOption[];
  doctors: DoctorOption[];
  onClose: () => void;
  onGenerated: (range: {
    fromDate: string;
    toDate: string;
  }) => Promise<void> | void;
};

function getCurrentDateKey() {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = String(
    currentDate.getMonth() + 1,
  ).padStart(2, "0");
  const day = String(
    currentDate.getDate(),
  ).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function addDaysToDateKey(
  dateKey: string,
  amount: number,
) {
  const date = new Date(`${dateKey}T00:00:00`);
  date.setDate(date.getDate() + amount);

  const year = date.getFullYear();
  const month = String(
    date.getMonth() + 1,
  ).padStart(2, "0");
  const day = String(date.getDate()).padStart(
    2,
    "0",
  );

  return `${year}-${month}-${day}`;
}


function isRecord(
  value: unknown,
): value is Record<string, unknown> {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}


function getResponseMessage(
  raw: unknown,
  fallback: string,
) {
  if (!isRecord(raw)) return fallback;

  if (typeof raw.message === "string") {
    return raw.message;
  }

  if (
    isRecord(raw.data) &&
    typeof raw.data.message === "string"
  ) {
    return raw.data.message;
  }

  return fallback;
}

export function DoctorShiftBulkGenerateModal({
  open,
  facilities,
  rooms,
  doctors,
  onClose,
  onGenerated,
}: DoctorShiftBulkGenerateModalProps) {
  const { message: messageApi } = App.useApp();
  const [form] =
    Form.useForm<BulkGenerateFormValues>();
  const [shiftSlots, setShiftSlots] = useState<
    ShiftSlotLookupItem[]
  >([]);
  const [slotsLoading, setSlotsLoading] =
    useState(false);
  const [confirmLoading, setConfirmLoading] =
    useState(false);
  const [error, setError] = useState<
    string | null
  >(null);

  const watchedFacilityId =
    Form.useWatch("facilityId", form) ?? "";
  const watchedSlotGroups =
    Form.useWatch("slotGroups", form) ?? [];

  const slotById = useMemo(
    () =>
      new Map(
        shiftSlots.map((slot) => [slot.id, slot]),
      ),
    [shiftSlots],
  );

  const roomOptions = useMemo(
    () =>
      rooms
        .filter(
          (room) =>
            room.facilityId === watchedFacilityId,
        )
        .map((room) => ({
          value: room.id,
          label: `${room.name}${
            room.floor
              ? ` · ${room.floor}`
              : ""
          }`,
        })),
    [rooms, watchedFacilityId],
  );

  const doctorOptions = useMemo(
    () =>
      doctors
        .filter(
          (doctor) =>
            doctor.status === "active" &&
            doctor.staffId &&
            doctor.facilityIds.includes(
              watchedFacilityId,
            ),
        )
        .map((doctor) => ({
          value: doctor.staffId,
          label: `${doctor.title} ${doctor.name} · ${doctor.specialty}`,
        })),
    [doctors, watchedFacilityId],
  );

  useEffect(() => {
    if (!open) return;

    const today = getCurrentDateKey();

    const timer = window.setTimeout(() => {
      form.resetFields();
      form.setFieldsValue({
        fromDate: today,
        toDate: addDaysToDateKey(today, 30),
        saveOnlyValid: true,
        slotGroups: [],
      });
      setShiftSlots([]);
      setError(null);
    }, 0);

    return () => {
      window.clearTimeout(timer);
    };
  }, [form, open]);

  useEffect(() => {
    if (!open || !watchedFacilityId) {
      return;
    }

    let cancelled = false;

    void Promise.resolve()
      .then(() => {
        if (!cancelled) {
          setSlotsLoading(true);
        }

        return getShiftSlotLookup({
          facilityId: watchedFacilityId,
          status: "active",
          limit: 40,
        });
      })
      .then((slots) => {
        if (cancelled) return;

        setShiftSlots(slots);
        form.setFieldsValue({
          slotGroups: slots.map((slot) => ({
            slotId: slot.id,
            assignments: [],
          })),
        });
      })
      .catch((loadError) => {
        if (cancelled) return;

        setShiftSlots([]);
        form.setFieldsValue({
          slotGroups: [],
        });
        setError(getErrorMessage(loadError));
      })
      .finally(() => {
        if (!cancelled) {
          setSlotsLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [
    form,
    open,
    watchedFacilityId,
  ]);

  function buildPayload(
    values: BulkGenerateFormValues,
  ): BulkGenerateDoctorShiftsInput {
    if (values.toDate < values.fromDate) {
      throw new Error(
        "Ngày kết thúc phải bằng hoặc sau ngày bắt đầu.",
      );
    }

    const slotAssignments =
      (values.slotGroups ?? [])
        .map((group) => {
          const assignments =
            (group.assignments ?? []).map(
              (assignment) => {
                const doctor = doctors.find(
                  (item) =>
                    item.staffId ===
                    assignment.staffId,
                );

                if (!doctor) {
                  throw new Error(
                    "Không tìm thấy thông tin nhân sự của bác sĩ đã chọn.",
                  );
                }

                return {
                  staffId:
                    assignment.staffId.trim(),
                  roleId: String(
                    doctor.roleId,
                  ),
                  roomId:
                    assignment.roomId.trim(),
                  workingDays:
                    assignment.workingDays,
                  maxAppointments: Number(
                    assignment.maxAppointments,
                  ),
                  status: assignment.status,
                };
              },
            );

          return {
            slotId: group.slotId.trim(),
            assignments,
          };
        })
        .filter(
          (group) =>
            group.assignments.length > 0,
        );

    if (slotAssignments.length === 0) {
      throw new Error(
        "Vui lòng phân công ít nhất một bác sĩ vào một khung ca.",
      );
    }

    return {
      facilityId: values.facilityId.trim(),
      fromDate: values.fromDate,
      toDate: values.toDate,
      slotAssignments,
      saveOnlyValid:
        values.saveOnlyValid ?? true,
    };
  }

  async function handleConfirm() {
    setError(null);

    try {
      const values =
        await form.validateFields();
      const payload = buildPayload(values);

      setConfirmLoading(true);

      const response =
        await confirmAutoGeneratedShifts(
          payload,
        );

      await onGenerated({
        fromDate: payload.fromDate,
        toDate: payload.toDate,
      });

      messageApi.success(
        getResponseMessage(
          response,
          "Tạo lịch trực nhiều ngày thành công.",
        ),
      );

      form.resetFields();
      onClose();
    } catch (confirmError) {
      const message =
        getErrorMessage(confirmError);

      setError(message);

      if (
        !(
          isRecord(confirmError) &&
          "errorFields" in confirmError
        )
      ) {
        messageApi.error(message);
      }
    } finally {
      setConfirmLoading(false);
    }
  }

  function handleCancel() {
    if (confirmLoading) {
      return;
    }

    form.resetFields();
    setShiftSlots([]);
    setError(null);
    onClose();
  }

  return (
    <Modal
      open={open}
      centered
      width={1120}
      title={null}
      footer={null}
      closable={false}
      onCancel={handleCancel}
      mask={{
        closable: !confirmLoading,
      }}
      destroyOnHidden
      styles={{
        body: {
          maxHeight: "82vh",
          overflow: "hidden",
        },
      }}
    >
      <div className="relative mb-5 border-b border-slate-200 pb-4 pr-12">
        <button
          type="button"
          aria-label="Đóng"
          disabled={confirmLoading}
          onClick={handleCancel}
          className="absolute right-0 top-0 z-10 flex h-9 w-9 items-center justify-center rounded-full text-slate-400 transition hover:bg-slate-100 hover:text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-start gap-3">
          <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-white">
            <Calendar className="h-5 w-5" />
          </span>

          <div>
            <Title
              level={4}
              className="!mb-1 !text-slate-950"
            >
              Tạo lịch trực nhiều ngày
            </Title>

            <Text type="secondary">
              Chọn khoảng ngày và phân công bác sĩ theo từng khung ca, phòng và ngày làm việc trong tuần.
            </Text>
          </div>
        </div>
      </div>

      <div
        className="pr-3"
        style={{
          maxHeight: "calc(82vh - 180px)",
          overflowY: "auto",
          scrollbarGutter: "stable",
        }}
      >
        {error ? (
        <Alert
          type="error"
          title={error}
          showIcon
          closable
          className="mb-4"
          onClose={() =>
            setError(null)
          }
        />
      ) : null}

      <Form<BulkGenerateFormValues>
        form={form}
        layout="vertical"
        requiredMark="optional"
        onValuesChange={(
          changedValues,
        ) => {
          if (
            "facilityId" in
            changedValues
          ) {
            const facilityId =
              changedValues.facilityId as string;

            setShiftSlots([]);
            setSlotsLoading(
              Boolean(facilityId),
            );
            form.setFieldsValue({
              slotGroups: [],
            });
          }
        }}
      >
        <Row gutter={[16, 0]}>
          <Col xs={24} lg={10}>
            <Form.Item
              name="facilityId"
              label="Cơ sở"
              rules={[
                {
                  required: true,
                  message:
                    "Vui lòng chọn cơ sở.",
                },
              ]}
            >
              <Select
                showSearch
                optionFilterProp="label"
                placeholder="Chọn cơ sở khám"
                options={facilities.map(
                  (facility) => ({
                    value: facility.id,
                    label: `${facility.name} (${facility.code})`,
                  }),
                )}
              />
            </Form.Item>
          </Col>

          <Col xs={24} sm={12} lg={5}>
            <Form.Item
              name="fromDate"
              label="Từ ngày"
              rules={[
                {
                  required: true,
                  message:
                    "Chọn ngày bắt đầu.",
                },
              ]}
            >
              <Input type="date" />
            </Form.Item>
          </Col>

          <Col xs={24} sm={12} lg={5}>
            <Form.Item
              name="toDate"
              label="Đến ngày"
              dependencies={[
                "fromDate",
              ]}
              rules={[
                {
                  required: true,
                  message:
                    "Chọn ngày kết thúc.",
                },
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    const fromDate =
                      getFieldValue(
                        "fromDate",
                      ) as string;

                    if (
                      !value ||
                      !fromDate ||
                      value >= fromDate
                    ) {
                      return Promise.resolve();
                    }

                    return Promise.reject(
                      new Error(
                        "Ngày kết thúc phải bằng hoặc sau ngày bắt đầu.",
                      ),
                    );
                  },
                }),
              ]}
            >
              <Input type="date" />
            </Form.Item>
          </Col>

          <Col xs={24} lg={4}>
            <Form.Item
              name="saveOnlyValid"
              label="Chỉ lưu lịch hợp lệ"
              valuePropName="checked"
            >
              <Switch />
            </Form.Item>
          </Col>
        </Row>

        <div className="mb-3 flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
          <div>
            <Text
              strong
              className="block text-slate-950"
            >
              Phân công theo khung ca
            </Text>

            <Text
              type="secondary"
              className="text-sm"
            >
              Mỗi bác sĩ chọn phòng, các ngày làm việc trong tuần và số lịch tối đa.
            </Text>
          </div>

          {watchedFacilityId &&
          !slotsLoading ? (
            <Tag color="blue">
              {shiftSlots.length} khung ca
            </Tag>
          ) : null}
        </div>

        {!watchedFacilityId ? (
          <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center">
            <Clock className="mx-auto h-7 w-7 text-slate-400" />

            <Text className="mt-3 block font-medium text-slate-700">
              Vui lòng chọn cơ sở
            </Text>

            <Text
              type="secondary"
              className="mt-1 block text-sm"
            >
              Các khung ca hoạt động của cơ sở sẽ hiển thị tại đây.
            </Text>
          </div>
        ) : slotsLoading ? (
          <div className="rounded-xl border border-slate-200 bg-slate-50 px-5 py-10 text-center">
            <Text type="secondary">
              Đang tải danh sách khung ca...
            </Text>
          </div>
        ) : shiftSlots.length === 0 ? (
          <Alert
            type="warning"
            showIcon
            title="Cơ sở chưa có khung ca hoạt động"
          />
        ) : (
          <Form.List name="slotGroups">
            {(groupFields) => (
              <div className="grid gap-4">
                {groupFields.map(
                  (
                    groupField,
                    groupIndex,
                  ) => {
                    const group =
                      watchedSlotGroups[
                        groupIndex
                      ];
                    const slot =
                      slotById.get(
                        group?.slotId ??
                          shiftSlots[
                            groupIndex
                          ]?.id ??
                          "",
                      );

                    if (!slot) {
                      return null;
                    }

                    const assignmentCount =
                      group?.assignments
                        ?.length ?? 0;

                    return (
                      <div
                        key={
                          groupField.key
                        }
                        className="overflow-hidden rounded-xl border border-slate-200 bg-white"
                      >
                        <Form.Item
                          name={[
                            groupField.name,
                            "slotId",
                          ]}
                          hidden
                        >
                          <Input />
                        </Form.Item>

                        <div className="flex flex-col justify-between gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3 sm:flex-row sm:items-center">
                          <div className="flex items-center gap-3">
                            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-slate-900 text-white">
                              <Clock className="h-5 w-5" />
                            </span>

                            <div>
                              <Text
                                strong
                                className="block text-slate-950"
                              >
                                {slot.name}
                              </Text>

                              <Text
                                type="secondary"
                                className="text-sm"
                              >
                                {slot.code} ·{" "}
                                {slot.startTime} -{" "}
                                {slot.endTime}
                              </Text>
                            </div>
                          </div>

                          <Tag
                            color={
                              assignmentCount >
                              0
                                ? "green"
                                : "default"
                            }
                          >
                            {assignmentCount >
                            0
                              ? `${assignmentCount} phân công`
                              : "Chưa phân công"}
                          </Tag>
                        </div>

                        <div className="p-4">
                          <Form.List
                            name={[
                              groupField.name,
                              "assignments",
                            ]}
                          >
                            {(
                              assignmentFields,
                              {
                                add,
                                remove,
                              },
                            ) => (
                              <div className="flex flex-col gap-3">
                                {assignmentFields.length ===
                                0 ? (
                                  <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-5 text-center">
                                    <Text
                                      type="secondary"
                                      className="text-sm"
                                    >
                                      Chưa có bác sĩ trong khung ca này.
                                    </Text>
                                  </div>
                                ) : null}

                                {assignmentFields.map(
                                  (
                                    assignmentField,
                                    assignmentIndex,
                                  ) => (
                                    <div
                                      key={
                                        assignmentField.key
                                      }
                                      className="rounded-lg border border-slate-200 bg-slate-50/70 p-3"
                                    >
                                      <div className="mb-2 flex items-center justify-between">
                                        <Text
                                          strong
                                          className="text-sm text-slate-700"
                                        >
                                          Phân công{" "}
                                          {assignmentIndex +
                                            1}
                                        </Text>

                                        <Button
                                          danger
                                          type="text"
                                          size="small"
                                          icon={
                                            <Trash2 className="h-4 w-4" />
                                          }
                                          onClick={() =>
                                            remove(
                                              assignmentField.name,
                                            )
                                          }
                                        >
                                          Xóa
                                        </Button>
                                      </div>

                                      <Row
                                        gutter={[
                                          12,
                                          0,
                                        ]}
                                      >
                                        <Col
                                          xs={24}
                                          lg={9}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "staffId",
                                            ]}
                                            label="Bác sĩ"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn bác sĩ.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              showSearch
                                              optionFilterProp="label"
                                              placeholder="Chọn bác sĩ"
                                              options={
                                                doctorOptions
                                              }
                                              notFoundContent="Cơ sở chưa có bác sĩ phù hợp"
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={12}
                                          lg={6}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "roomId",
                                            ]}
                                            label="Phòng"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn phòng.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              showSearch
                                              optionFilterProp="label"
                                              placeholder="Chọn phòng"
                                              options={
                                                roomOptions
                                              }
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={6}
                                          lg={4}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "maxAppointments",
                                            ]}
                                            label="Số lịch tối đa"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Nhập số lịch.",
                                              },
                                            ]}
                                          >
                                            <InputNumber
                                              min={1}
                                              className="w-full"
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col
                                          xs={24}
                                          md={6}
                                          lg={5}
                                        >
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "status",
                                            ]}
                                            label="Trạng thái"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn trạng thái.",
                                              },
                                            ]}
                                          >
                                            <Select
                                              options={[
                                                {
                                                  value:
                                                    "available",
                                                  label:
                                                    "Còn trống",
                                                },
                                                {
                                                  value:
                                                    "off",
                                                  label:
                                                    "Nghỉ",
                                                },
                                              ]}
                                            />
                                          </Form.Item>
                                        </Col>

                                        <Col xs={24}>
                                          <Form.Item
                                            name={[
                                              assignmentField.name,
                                              "workingDays",
                                            ]}
                                            label="Ngày làm việc trong tuần"
                                            rules={[
                                              {
                                                required:
                                                  true,
                                                message:
                                                  "Chọn ít nhất một ngày làm việc.",
                                              },
                                            ]}
                                          >
                                            <Checkbox.Group
                                              options={
                                                WORKING_DAY_OPTIONS
                                              }
                                              className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"
                                            />
                                          </Form.Item>
                                        </Col>
                                      </Row>
                                    </div>
                                  ),
                                )}

                                <Button
                                  type="dashed"
                                  block
                                  icon={
                                    <Plus className="h-4 w-4" />
                                  }
                                  onClick={() =>
                                    add({
                                      staffId:
                                        "",
                                      roomId: "",
                                      workingDays:
                                        [
                                          "MON",
                                          "TUE",
                                          "WED",
                                          "THU",
                                          "FRI",
                                        ],
                                      maxAppointments:
                                        8,
                                      status:
                                        "available",
                                    })
                                  }
                                >
                                  Thêm bác sĩ vào{" "}
                                  {slot.name}
                                </Button>
                              </div>
                            )}
                          </Form.List>
                        </div>
                      </div>
                    );
                  },
                )}
              </div>
            )}
          </Form.List>
        )}

      </Form>
      </div>

      <div className="mt-4 flex flex-col-reverse justify-end gap-2 border-t border-slate-200 pt-4 sm:flex-row">
        <Button
          disabled={confirmLoading}
          onClick={handleCancel}
        >
          Hủy
        </Button>

        <Button
          type="primary"
          loading={confirmLoading}
          onClick={() =>
            void handleConfirm()
          }
        >
          Tạo lịch trực nhiều ngày
        </Button>
      </div>
    </Modal>
  );
}
